### ISSUE TITLE
Anpassen des Zuweisung eines Projektes zu einem Semester beim Enreichen

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#100]
Ein Dozent P hat in der Periode 17FS ein Projekt erfasst, dieses dann aber erst eingereicht, als bereits die Periode 17HS eröffnet bzw. aktiv war. Das Projekt erscheint dann auch richtig in der Rubrik "Projekte zur Freigabe" und ich nehme an, dass, wenn es freigegeben wird, dann auch der richtigen  Preiode zugewiesen wird. Ich habe das Projekt jedoch abgelehnt, und jetzt erscheint es in der Rubrik "Alle in Bearbeitung", jedoch in der alten Periode (17FS) und nicht in der aktuellen Periode (17HS).

Vorschlag: Die Projektperiode eines Projektes sollte bereits beim Einreichen angepasst werden, so dass ein abgewiesenes Projekt in der Liste der Projekte "Alle in Bearbeitung" der aktuellen Periode erscheint.

**Comment by deiruch** [comment]
Gratulation zum runden Issue-Jubiläum!

Bei "Alle in Bearbeitung" werden folgende Projekte aufgelistet:
- Projekte im eigenen Institut
- Bearbeitet seit Semesterbeginn
- Noch nicht eingereicht

Ob das Projekt von Dozent P in dieser Liste auftaucht hat also nichts mit dem zugeordneten Semester zu tun. Wären für dich andere Filter-Kriterien sinnvoller? Wir könnten z.B. auch eingereichte Projekte anzeigen.

**Comment by dgruntz** [comment]
Verstehe ich nicht ganz. Das Projekt von P erscheint in der Liste "alle in Bearbeitung", aber nicht im aktuellen Semester (17HS) sondern im letzten Semester (17FS). P hat dieses Projekt dann erfasst, hat es jetzt aber für das aktuelle Semester eingereicht und ich habe es abgelehnt. Hätte jetzt erwartet dass es unter "Alle in Bearbeitung" in der aktuellen Periode (17HS) erscheint (da ich es zumindest gestern, also in der aktuellen Periode, abgelehnt habe), aber es ist in die letzte Periode zurückgefallen, das war mein Punkt.

Andere Filter helfen da nicht, da eben das Semester falsch ist (bzw. nicht nachgeführt wurde).

**Comment by deiruch** [comment]
Das Semester war/ist nicht falsch, es ist ein Filter-Problem. Ich habe die Logik vereinfacht und angepasst. Mit dem nächsten Release sollte das Problem gefixt sein.

In der Zwischenzeit solltest Du beim Semester-Filter einfach "Alle Semester" anwählen, dann funktioniert es, wie es soll.
