### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#103]
Ich habe eben einen Export gemacht mit allen Projekten, die im 16HS enden und habe mich gefragt, ob die Bachelor-Projekte, die am 24.03.2017 enden auch in dieser Liste aufgeführt sind. Effektiv sind im resultierenden Excel jedoch alle Projekte drin die am 20.01.17, 24.03.17 oder 18.08.17 enden aufgelistet, d.h. bei diesem Filter "Endende Projekte / 16HS" stimmt etwas noch nicht.

![image](https://cloud.githubusercontent.com/assets/1516800/25798767/c0677554-33e2-11e7-8748-139982b80d0f.png)

Alle im Excel aufgelisteten Projekte sind am 19.09.16 gestartet worden. Werden vielleicht trotzdem alle "im 16 HS *startenden* Projekte" aufgelistet?

**Comment by deiruch** [comment]
@flavio99 Kannst Du kurz Testen und Deployen?
