### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#105]
Wollte eben ein Projekt veröffentlichen und habe dabei folgenden Fehler gesehen:

![image](https://cloud.githubusercontent.com/assets/1516800/25955926/c1faab90-366a-11e7-99c4-57422b4b7c38.png)

Was für ein State ist da falsch?

**Comment by deiruch** [comment]
Ich habe mal einen Fix commited, der das Problem lösen sollte/könnte. @flavio99 Kannst Du das bei Gelegenheit mal Testen und Publishen?

**Comment by flavio99** [comment]
Habe es lokal getestet und gepublished.

**Comment by dgruntz** [comment]
Besten Dank! Ich konnte das entsprechende Projekt jetzt veröffentlichen.
