### ISSUE TITLE
Projekt muss in einem einzigen Semester durchgeführt werden.

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#106]
Ich habe bei einem Projekt das Häkchen bei

    [X] Projekt muss in 1 Semester durchgeführt werden.

gesetzt, aber dennoch erscheint auf dem Flyer unter Bemerkungen der Text "Dieses Projekt muss in einem einzigen Semester durchgeführt werden" nicht. Es steht da lediglich die Information für welche Studierenden das Projekt reserviert ist.

Projekt-ID: 305

![image](https://cloud.githubusercontent.com/assets/1516800/26200870/a0a71a6c-3bd0-11e7-9de1-10841f024861.png)

**Comment by dgruntz** [comment]
Ich habe eben das Flag rausgenommen / gespeichert / Flag wieder gesetzt / gespeichert, aber die Meldung erscheint noch nicht auf dem Flyer. Oder gilt diese Information nur für IP6-Projekte?

**Comment by flavio99** [comment]
Ich habe diese Bemerkung extra entfernt, da dies nun Standart sein sollte.

**Comment by flavio99** [comment]
Könnte auch sein das es angezeigt werden sollte jedoch nur schwarz. Bin nicht mehr sicher was wir abgemacht haben.

**Comment by deiruch** [comment]
Sollte einfach Schwarz statt Rot sein.

**Comment by flavio99** [comment]
Im Code wird noch nach IP6 gefiltert. Desshalb wird es bei dir nicht angezeigt.

**Comment by deiruch** [comment]
Es sollte nicht gefiltert werden.

**Comment by deiruch** [comment]
Auch IP5 können 1/2 Semester dauern.

**Comment by dgruntz** [comment]
Besten Dank, jetzt erscheint die Information. Eigentlich ist es fast wichtiger bei IP5-Projekten diese Information anzuzeigen, denn IP6-Projekte dauern alle gleich lang (bis auf die Variante-B-Projekte, aber die können von den Studierenden nicht gewählt werden, d.h. diese müssen Sie vorab so beantragen).
