### ISSUE TITLE
Ablehnungs-Email

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#115]
Wenn ein Projekt vom Koordinator abgelehnt wird, dann kann er seine Begründung ja direkt in der Plattform beschrieben und dieser Text wird dann dem Betreuer, der die Arbeit eingereicht hat, zugestellt. 

Damit der Koordinator eine Kontrolle hat was er kritisiert hat wäre es hilfreich, wenn er die an den Betreuer verschickte email (insbesondere im Fall einer Ablehnung) auch Cc erhält. Die Bestätigungsemails müssten jedoch nicht auch Cc an den Koordinator verschckt werden, aber damit könnte ich leben.

**Comment by deiruch** [comment]
Das habe ich schon implementiert, ist nur noch nicht deployed.

**Comment by flavio99** [comment]
Ist deployed.
