### ISSUE TITLE
Zu Beginn wird nur 1 Reservationsfeld angezeigt

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#12]
Je nach Anzahl studierender sollten 1 bzw. 2 Reservationsfelder eingeblendet werden. Aktuell wird erstmalig nur 1 Feld angezeigt, obwohl per Default 2er-Projekte erstellt werden.

**Comment by StephenRUK** [comment]
AddNewProject.aspx.cs:
Methode UpdateReservationNameTwoVisibility() wurde bisher nur beim Bearbeiten eines Projekts und beim onChange der entsprechenden Dropdown-Menüs ausgeführt. Ich habe die Ausführung nach Page_Load() verschoben.

Manuell getestet - bei Erstellung & Bearbeitung stimmt die Anzahl Reservations-Felder in jedem Fall.
