### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#120]
Die folgenden Links auf der Seite https://www.cs.technik.fhnw.ch/prostud/AdminPage zeigen ins Leere:

![image](https://user-images.githubusercontent.com/1516800/29306966-188c0c9e-81a0-11e7-88c8-654060ccd7e2.png)

**Comment by flavio99** [comment]
Wurde schon mit #117 behoben, aber noch nicht veröffentlicht.
