### ISSUE TITLE
Zip mit allen ProjektArtefakten

### ISSUE THREAD

**Issue by flavio99** [i4Ds/ProStudCreator#125]
Auf der Infoseite sollte es möglich sein, ein Zip mit allen Projektartefakte herunterzuladen.

**Comment by deiruch** [comment]
Finde das Design etwas eigenartig... Das ist das erste Mal, dass etwas im Header platziert wurde - daher wirkt es auf mich inkonsistent. Vielleicht gibts einen besseren Platz?

Und vermutlich macht der Link nur Sinn, wenn auch Files zum Runterladen vorhanden sind, andererseits sollte kein Link da stehen, oder?
