### ISSUE TITLE
Server Error wenn in Formular für "Verrechnung" E-Mail-Feld leer

### ISSUE THREAD

**Issue by wweck** [i4Ds/ProStudCreator#127]
Bei den Adressangaben zur "Verrechnung" ist "E-Mail" kein Pflichtfeld. Bleibt es leer, gibt es einen "Server Error".

**Comment by dgruntz** [comment]
Konnte ich reproduzieren:
![image](https://user-images.githubusercontent.com/1516800/30490366-0494c750-9a3a-11e7-98a1-005afd9b0c1e.png)
