### ISSUE TITLE
Projektnummern korrekt vergeben

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#13]
Aktuell werden Projektnummern doppelt vergeben. Das sollte nicht passieren. Pro Semester und Institut darf jede Projektnummer nur einmal vergeben werden.

Sobald ein Projekt einmal eingereicht wurde sollte die Projektnummer nicht mehr geändert werden. Projektnummern sollten immer zweistellig sein.

**Comment by StephenRUK** [comment]
Mein Test hat gezeigt, dass Projektnummern i.d.R. korrekt erzeugt werden, wenn Projekte nacheinander veröffentlicht werden.

Zieht man jedoch ein Projekt wieder zurück, wird seine 'damalige' Projektnummer dem als nächstes veröffentlichten Projekt zugewiesen.

To do:
Extensions.cs, Publish(): Das where-Statement welche die bestehenden Projektnummern holt muss angepasst werden, sodass auch zurückgezogene Projekte berücksichtigt werden (siehe ProjectState Conditions)

**Comment by StephenRUK** [comment]
Update:
* Projektnummer wird nun korrekt vergeben innerhalb einer Abteilung
* "In Progress" Projekte (d.h. zurückgezogene), welche bereits eine Projektnummer erhalten haben, werden ebenfalls berücksichtigt.

To do:
* Bei einem Abteilungswechsel wird die Projektnummer noch mitgenommen, dies kann zu doppelten Projektnummern in einer Abteilung führen. Projektnummer muss beim Speichern nochmals kontrolliert werden (vlt. insbesondere in Hinsicht auf die Abteilung)

**Comment by StephenRUK** [comment]
Bei Abteilungswechsel wird nun auch eine neue Projektnummer generiert, falls eine schon vorhanden war. Dies verhindert Doppelvergaben der Nummer. All Fixed!
