### ISSUE TITLE
Überwachung des Taskhandler

### ISSUE THREAD

**Issue by flavio99** [i4Ds/ProStudCreator#132]
Der Taskhandler wird momentan alle 20 minuten ausgeführt. Jedoch bemerkt man nicht, wenn dieser nicht mehr läuft, oder länger als 20 minuten hat. 
Der Taskhandler sollte irgendwie überwacht werden können, sodas man im Falle eines Fehler benachrichtigt wird.

**Comment by dgruntz** [comment]
Ist grösstenteils erldigt. Jeder Task der ausgeführt wird wird in einer Tabelle gespeichert, und diese können auf einer speziellen seite Dargestellt werden. Aber automatische Benachrichtigung fehlt noch.

@Beckicious meint dass dieses Feature nicht nötig ist.
