### ISSUE TITLE
Angabe 1/2 Semester bei BB-Projekten

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#134]
Wenn man ein Projekt erfasst welches von Studierenden eingereicht worden ist, dann gibt man ja den Namen der Studierenden ein. Gut wenn man auch gerade angeben könnte, ob das Projekt über 1 oder 2 Semester läuft. Aktell kann bei der Option "muss in einem Semester durchgeführt werden" ein Kreuz setzen, aber eigentlich ist das die falsche Beschreibung, denn wenn es nicht angekreuz ist wissen wir nicht, ob das Projekt nun in einem oder in zwei Semestern durchgeführt wird.

**Comment by deiruch** [comment]
Vorschlag #138
