### ISSUE TITLE
Neue Haupt-/Nebenbetreuer erfassen?

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#136]
Aktuell wird Anwendern nicht klar sein, wie man neue Haupt-/Nebenbetreuer erfassen kann. Nett wäre vielleicht ein mailto-Link, mit dem man ein E-Mail an uns schicken kann.

**Comment by dgruntz** [comment]
Institutsverantworliche sollten diese Daten auf einer entsprechenden Admin-Seite erfassen können.
