### ISSUE TITLE
1/2 Semesterdauer auf andere Art erfassen

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#138]
Nur BB-Studierende, die beim Auftraggeber angestellt sind, dürfen Projekte über 2 Semester machen. In solchen Fällen ist das Projekt auch jeweils für die Studierenden reserviert. Darum, folgender Vorschlag:

* Checkbox "Muss in 1 Semester durchgeführt werden" aus Formular und PDFs entfernen
* Bei reservierten Arbeiten (Namen & Email von Studis wurde eingetragen) eine Dropdown-Box einblenden/enablen, bei der man schon beim Erfassen angeben muss, ob das Projekt in 1/2 Semestern durchgeführt werden wird.

**Comment by dgruntz** [comment]
> Nur BB-Studierende, die beim Auftraggeber angestellt sind, dürfen Projekte über 2 Semester machen. I

Das gilt bei einem IP6, aber ein P5 können *alle* BB-Studierenden über 2 Semester hinweg machen, d.h. auch wenn die Studierenden ein normales Projekt wählen, daher braucht es (also Information an BB-Studierenden) die Information, ob ein frei auf dem Markt verfügbares Studierendenprojekt auch über 2 Semester laufen darf. Die Option "Muss in einem Semester durchgeführt werden"  macht also schon Sinn.

**Comment by deiruch** [comment]
Stimmt. Vermutlich würde ein Re-Design der Maske in diesem Bereich Sinn machen...

**Comment by dgruntz** [comment]
Projekte über 2 Semester existieren nicht mehr. Issue hat sich damit erledigt.
