### ISSUE TITLE
Kundentyp

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#140]
Wenn man bei der Eingabe den Kundentyp als Intern erfasst

![image](https://user-images.githubusercontent.com/1516800/32441799-59c6fd96-c2f9-11e7-990f-f9818763be23.png)

und das Projekt dann speichert, dann verschwindet diese Eingabe wieder, d.h. es wird auf den Kudnentyp "Privatperson" zurückgesetzt.

PS: Was ist eigentlich die Idee hinter dieser Eingabe? Einfach dass man die Daten der Kontaktperson auch erfasst hat? Wird diese Adresse dann wenn man die Verrechnungsadresse erfasst gerade als Default übernommen?

**Comment by deiruch** [comment]
(Zum PS: Ja, genau - die Anschrift dient als Rechnungsadresse)
