### ISSUE TITLE
Workflow mit überlangen Texten verbessern

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#15]
Die Plattform sollte Benutzer dabei unterstützen, zu lange Texte zu kürzen. Es könnte z.B. während dem Editieren live angezeigt werden, wie (viel zu) lange der aktuelle Text ist. So könnte man live kürzen, bis es passt - statt zu kürzen, speichern, PDF anschauen, etc.

**Comment by StephenRUK** [comment]
Todo: 'Optimale' Textlänge ermitteln, die im PDF Export noch korrekt und leserlich angezeigt wird.
Anzeige der Textlänge (und Anzahl Zeichen darüber) sollte relativ trivial sein.

**Comment by StephenRUK** [comment]
Die Seitenzahl wird nun in einem regelmässigen Intervall überprüft und bei den Speicher usw. Buttons rot (> 1 Seite) bzw grün (=1 Seite) angezeigt.
