### ISSUE TITLE
Projektnummern werden nicht korrekt generiert

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#153]
Beim Veröffentlichen werden Projekten keine Projektnummern zugewiesen.

**Comment by dgruntz** [comment]
Erkennt man auch daran, dass in der Übersicht die Nummern nicht angezeigt werden:

![image](https://user-images.githubusercontent.com/1516800/33017902-7ada5860-cdf4-11e7-80e1-dab980cb2a4c.png)
