### ISSUE TITLE
Beim Überarbeiten eines Projekts verschwinden ältere Versionen aus der History

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#154]
Beispiel: https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=571

Nach einigen Textänderungen sind die History-Einträge von Simon Schubiger verschwunden...?!?

**Comment by JonasDev99** [comment]
Es gibt keine weiteren Projekte mit dem Namen ["Erkennung von Zonen in Architekturplänen"](https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=571) in der DB die in der ProjektHistory nicht aufgeführt sind, nur das Projekt ["Analyse und Vereinfachung von Architekturplänen" ](https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=132) das von der selben Firma stammt...

**Comment by JonasDev99** [comment]
Ich habe zweit Projekte gfunden : https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=132 und  https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=45. Ist vermutlich noch ein alter Fehler den ich in der DB nicht korrigiert habe.

**Comment by JonasDev99** [comment]
Es gibt keine älteren Versionen von diesem Projekt in der DB. Ich habe nur das Projekt https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=132 gefunden, wobei es sich jedoch nicht um das selbe handelt. Es könnte sein, dass es sich bei den Verschwundenen Versionen um die Versionen handelte, die durch einen Bug erzeugt wurden.
