### ISSUE TITLE
Semester-Zuteilung ist suboptimal

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#165]
Projekte, die im September 2017 eingereicht wurden (z.B. Id 287, 203 oder 361), wurden fälschlicherweise mit SemesterId=7 in der Datenbank abgelegt. Diese Projekte hätten SemesterId=10 erhalten müssen, da das PublishedDate lange nach SemesterId=7 Start lag.

**Comment by JonasDev99** [comment]
Könnte ein Fehler meinerseits gewesen sein, da ich einmal die Semesterdaten von mehreren Projekten manuell bearbeiten musste. Evtl. habe ich da die Reihennummer mit der Id verwechselt oder so. Am code habe ich jedenfalls nie etwas geändert.
