### ISSUE TITLE
Kann schon wieder keine Projekte mehr einreichen

### ISSUE THREAD

**Issue by wweck** [i4Ds/ProStudCreator#169]
Beim Versuch, ein Projekt einzureichen über den Button unten an der ausführlichen Projektbeschreibung erscheint die Meldung, ich müsse E-Mail Adressen für Studenten angeben, für die das Projekt reserviert sei. Das Projekt ist aber für niemanden reserviert und es sind auch keine Namen in den entsprechenden Feldern angegeben.

Beim Versuch dasselbe Projekt aus er Übersicht heraus einzureichen, passiert einfach nichts. Keine Meldung, keine Veränderung.

**Comment by JonasDev99** [comment]
um welches Projekt handelt es sich? ID?

**Comment by wweck** [comment]
Wenn id das ist, was im URL steht, dann 899.

**Comment by JonasDev99** [comment]
Sollte wieder möglich sein.
