### ISSUE TITLE
UX: "Reserviert für" wird disabled, wenn Vorgängerprojekt ausgewählt wurde

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#173]
...und das ist auch gut so.

Aber ein erklärender Text unter den Feldchen, woher jetzt diese Namen stammen und warum man sie nicht ändern kann wäre für einige User nützlich. Manche verstehen nicht, weshalb sie die Namen nicht ändern können.

**Comment by dgruntz** [comment]
Vielleicht wäre auch ein Kommentar bei der DropDownBox
![image](https://user-images.githubusercontent.com/1516800/33771840-da0b77aa-dc32-11e7-9c11-32ae014ba7eb.png)
hilfreich, damit man gerade weiss was diese Auswahl bewirkt. Ich hatte einen Nutzer der ein freies Folgeprojekt definiert hat und das Vorgängerprojekt hier ausgeählt hat und sich dann gewundert hat dass die Studierenden bereits gesetzt waren.
