### ISSUE TITLE
Doppelte Projekte

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#177]
Habe eben ein Projekt veröffentlicht, und danach war es immer noch in der Liste der freizugebenden Projekte aufgeführt. Habe es danach nochmals freigegeben mit dem Resultat, dass es jetzt doppelt vorhanden ist:

Es handelt sich um folgende Projekte:

![image](https://user-images.githubusercontent.com/1516800/33771720-619adae0-dc32-11e7-9c2c-201b2a05d56a.png)

Ich habe das zweite nun wieder gelöscht. Aber da scheint irgendwo ein grosser Bock versteckt zu sein!

**Comment by deiruch** [comment]
Resolutions:
[ ] Code review
[ ] Check constraints
[ ] Consistency checks in C# part (regular or at strategic state transitions)
[ ] Change database model to avoid the problem altogether (infeasible?)
