### ISSUE TITLE
Kundenkontakt: Telefonnummer hinzufügen

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#192]
Beim Erfassen eines Kundenkontaktes wäre es noch praktisch wenn neben den jetzt bereits erfassten Daten auch noch eine Telefonnummer eingegeben werden könnte.

![image](https://user-images.githubusercontent.com/1516800/35200139-fe34863c-ff08-11e7-8f74-20ef07eae0ca.png)

**Comment by deiruch** [comment]
Duplicate of #236

**Comment by dgruntz** [comment]
Scheint ein grosser Bedarf zu sein nach diesem Feature wenn das bereits zweimal erfasst worden ist ;-)
