### ISSUE TITLE
Include the project category labels in the "Projektliste in Excel"

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#196]
Dominik wants to allow students to filter projects by category in ProApp. For this, having the project category labels in the exported Excel sheet would be nice.

(Or, perhaps, having a different way to transfer this data altogether? REST?)

**Comment by dgruntz** [comment]
Which part would be the REST server? Would ProApp query the data from Prostud? Or vice versa?
Probably it would make sense if the data of available projects could be queried from Prostud.

**Comment by dgruntz** [comment]
Hat Jonas (?) erledigt, auf jeden Fall sind die Projekte in Proapp filterbar.
