### ISSUE TITLE
Projekte können nicht mehr abgelehnt werden.

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#197]
Wenn ich in einem Projekt auf "Ablehnen" klicke, z.B. auf
https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=555
dann verschwindet einzig der "Ablehnen" Knopf, aber das projekt ist weiterhin in der Liste.

**Comment by deiruch** [comment]
Das Projekt verbleibt im Status "veröffentlicht".

Wenn man danach auf "Speichern & Schliessen" klickt, erscheint das Projekt danach mehrfach in der Liste der veröffentlichten Projekte.

**Comment by dgruntz** [comment]
Aktuell ist die Funktion zumindst mal deaktiviert.

![image](https://user-images.githubusercontent.com/1516800/35808451-18cd6328-0a86-11e8-8664-60bb78d26360.png)
