### ISSUE TITLE
Sortieren der Projektlisten ermöglichen

### ISSUE THREAD

**Issue by StephenRUK** [i4Ds/ProStudCreator#20]
Momentan wird nach der Projektnummer sortiert. Es sollte möglich sein, nach jeder Spalte zu sortieren.

**Comment by StephenRUK** [comment]
GridView unterstützt automatisches Sortieren, falls die DataSource dies unterstützt, und diese nicht programmatisch gesetzt wird: https://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.gridview.allowsorting%28v=vs.110%29.aspx

**Comment by deiruch** [comment]
Duplikat von #11

**Comment by StephenRUK** [comment]
Hinweis: Die Daten der GridView werden zurzeit programmatisch aufbereitet und somit kann die eingebaute Sortierung nicht verwendet werden. A) könnten die Daten evtl. direkt an die GridView gebunden werden oder B) müsste die Sortierung selber entwickelt werden. Siehe Microsoft-Link im letzten Kommentar.
