### ISSUE TITLE
Eine gute Lösung für das abfüllen der Log-Felder finden

### ISSUE THREAD

**Issue by JonasDev99** [i4Ds/ProStudCreator#202]
Zurzeit müssen die Log-Felder von Hand in der DB eingetragen werden, was ziemlich mühsam ist.

**Comment by deiruch** [comment]
Care to explain the issue in detail? Unclear what is meant. :(

**Comment by JonasDev99** [comment]
I think I meant that the grades have to be entered with the SqlServerManager...

**Comment by deiruch** [comment]
But ProjectInfoPage does allow advisors to enter grades? Did you mean that?

**Comment by dgruntz** [comment]
Erfüllt, da die Daten über die Plattform gesetzt werden können.
