### ISSUE TITLE
Projektdauer (1/2 Semester)

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#206]
Die Option "Projekt muss in 1 Semester durchgeführt werden" kann gelöscht werden

![image](https://user-images.githubusercontent.com/1516800/37967038-705858d0-31ca-11e8-9f30-e134d65e129f.png)

In Zukunft werden ALLE Projekte nur noch eine Dauer von einem Semester haben, daher erübrigt sich diese Option.

**Comment by deiruch** [comment]
Kurze/lange P5-Varianten gibts doch aber weiterhin und haben doch eine Relevanz (z.B. Ferienpläne)?

Oder sagen wir einfach: Alle Betreuer & Kunden müssen sich so einrichten, dass auch die lange Variante möglich ist? Sind ja auch nur wenige Wochen...

**Comment by dgruntz** [comment]
Genau. Das gilt heute bereits für Projekte, die als IP5 oder IP6 gewählt werden können, und da haben wir nie eine Unterscheidung gemacht. Wenn man das eng als ein Semester interpretieren würde, dann dürfte ja kein IP6 diesen Tag tragen, aber das war nie mein Verständnis dieses Flags. Mit diesem Flag konnte man meiner Meinung nach angeben, ob sich ein Projekt auch für ein IP5/BB-55-Wochenprojekt eignet oder als IP6-Variante-B Projekt (wobei diese ja nicht mehr gibt).

**Comment by deiruch** [comment]
Fixed.
