### ISSUE TITLE
The tables in the admin-view do not get correctly populated

### ISSUE THREAD

**Issue by JonasDev99** [i4Ds/ProStudCreator#212]
![image](https://user-images.githubusercontent.com/25738474/39760640-245d267c-52d6-11e8-9425-2584cf79b508.png)

The project number column doesn't get populated but the number is in the title. It already works for the projectlist page.

**Comment by deiruch** [comment]
FYI: Project numbers will only be assigned when a project is published.

**Comment by JonasDev99** [comment]
@deiruch This means the column can be removed from the admin view, right?
