### ISSUE TITLE
Auch nicht-admins sollten Vergangene/Aktuelle/Neue veröffentlichte Projekte einsehen können

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#22]
Projekte sollten read-only oder PDF der Projekte anschauen können.

**Comment by StephenRUK** [comment]
Von anderen Nutzern veröffentlichte Projekte können bereits eingesehen werden, auch als nicht-admin. Siehe z.B. Projektauflistung 'laufendes Semester' - PDF-Export ist möglich.
Resolved.
