### ISSUE TITLE
Duplicate Projects

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#229]
Ich habe eben die Projektliste exportiert und gesehen dass das Projekt 18HS_IMVS08 doppelt erfasst ist oder doppelt in das Excel exportiert wird:

![image](https://user-images.githubusercontent.com/1516800/40825200-344baece-6577-11e8-90f5-06256535c632.png)

Die beiden Projekte haben aber unterschiedliche Primäschlüssel / Referenzen.

Vielleicht hängt dies auch mit [issue/228](https://github.com/i4Ds/ProStudCreator/issues/228) zusammen.

**Comment by deiruch** [comment]
Duplicate of #228
