### ISSUE TITLE
Abgelehnte Projekte können nicht erneut eingereicht werden?

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#23]
Ich kann z.B. https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=22 nicht erneut für das nächste Semester einreichen - da der Button "Einreichen" nicht sichtbar ist.

**Comment by deiruch** [comment]
Also, bei mir funktioniert's noch nicht. Ich kann Projekt #22 nicht erneut einreichen (Button ist unten nicht sichtbar).

**Comment by StephenRUK** [comment]
Ich habe die Bedingung nun so angepasst wie in deiner Mail beschrieben, werde das noch committen/publishen:
ShibUser.IsAdmin() || (_p.UserCanEdit() && _p.State != ProjectState.Submitted && _p.State != ProjectState.Published)

**Comment by StephenRUK** [comment]
"Ins nächste Semester" Button wurde abgeschafft.
Aktuelles Vorgehen:
- Alte Projekte können vom Admin abgelehnt werden
- Projekt-"Owner" sehen dann das Projekt in ihrer Liste und können dieses Bearbeiten & neu einreichen (kommt automatisch ins nächste Semester aufgrund des Datums)
