### ISSUE TITLE
File upload/download on ProjectInfoPage doesn't handle umlauts

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#239]
Example https://www.cs.technik.fhnw.ch/prostud/ProjectInfoPage?id=1254

Upload and downloading the file "iRuettä - Dokumentation.pdf" leads to a file called "iRuettÃ¤ - Dokumentation.pdf".

Tested with Edge/Win10.

**Comment by dgruntz** [comment]
Funktioniert mit Windows 7 (huch) und Chrome, d.h. es wird der richtige Dateiname verwendet.

@deiruch besteht bei Dir das Problem noch?
