### ISSUE TITLE
"SG I" (statt IMVS/i4Ds)-User können sich nicht einloggen

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#24]
Markus Oehninger erhält beim Anmelden eine UnauthorizedAccessException (vermutlich aus Site.Master):

member;staff, OU=Standard,OU=Users,OU=62_I,OU=WI,OU=18,OU=adm,OU=Prod,DC=adm,DC=ds,DC=fhnw,DC=CH

Vermutlich ist er falsch erfasst (OU=WI ?!?), aber er sollte Zugriff erhalten. Man könnte die Zugriffskontrolle auf alle Mitarbeiter im SG I (OU=62_I ?) ausdehnen. Man muss aber überlegen, ob bzw. welchem Institut man solche User zuweist. (Default Combobox, Sichtbarkeit/Filtern in Listen, ...)

**Comment by StephenRUK** [comment]
Zur AD-Struktur weiss ich nichts, aber die Zugehörigkeit zu IMVS/i4Ds wird ja über den LDAP Pfad ermittelt. Sollte Markus Oehningers Benutzerkonto dann nicht in einer entsprechenden OU sein, bzw. wer entscheidet dies?

**Comment by deiruch** [comment]
Markus Oehninger ist anscheinend direkt vom SG I angestellt, nicht vom i4Ds/IMVS. Es gibt einige solcher Fälle.

Diese User sollten trotzdem Projekte erfassen und anschauen können.

**Comment by StephenRUK** [comment]
Bestätigt durch Markus Oehninger, Mitarbeiter Studiengang Informatik können sich nun einloggen.
