### ISSUE TITLE
Replace Verrechnungsstatus with ProjectOutcome

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#241]
BillingStatus should be removed. A project can be have the following outcomes:
* Abgebrochen
* Abgebrochen (Pauschale CHF 500.-)
* Abgeschlossen

These existing outcomes in BillingStatus are already covered by other fields:
* Ausbildungsstätte oder gemeinnützige Institution: ClientType (see #240)
* Internes Projekt: ClientType
* Ungenügend für Rechnung: Student grades
* BB-Studierende mit Arbeitgeber-Projekt: Reserved for Students?
* Verlängerung von P5 auf P6: PreviousProjectID

**Comment by persillie** [comment]
Ich habe hier einfach die Anforderung, dass das zur Verrechnung generierte Excel File nicht verändert wird, da das offenbar in diesem Format bei Hanny eintreffen muss.

**Comment by dgruntz** [comment]
Wenn ein Projekt abgebrochen wird (Button `Abbruch`) dann wird der Verrechnungsstatus automatisch auf "Abgebrochen" gesetzt. Die zweite Option, `Abgebochen (Pauschale CHF 500.00)` wurde praktisch nie vergeben. 

Dozenten können neu nur noch folgende Verrechnungsstati definieren:

![image](https://user-images.githubusercontent.com/1516800/63511891-acaa3680-c4e2-11e9-9fd5-fbf1c718603a.png)
