### ISSUE TITLE
Integrate FAQ into relevant places

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#248]
Perhaps as a tooltip? Something like that.

Searching the FAQ is currently not user friendly.

**Comment by deiruch** [comment]
Fixed by 170f479f2b7898bf74d60da4609318da472ac79d

**Comment by dgruntz** [comment]
Unklar. Wo sollten Tooltips genau eingefügt werden?
=> Falls wirklich Bedarf bitte neues Issue eröffnen (mit präziserer Berschreibung).
