### ISSUE TITLE
Newlines werden im PDF nicht übernommen

### ISSUE THREAD

**Issue by StephenRUK** [i4Ds/ProStudCreator#25]
Wenn in der Beschreibung, Problemstellung usw. ein Zeilenumbruch gemacht wird, werden diese anscheinend nicht im generierten PDF übernommen. Wichtig z.B. für Auflistungen oder Absätze im allgemeinen.

Beispiel: Projekt ID 13 (i4Ds Nr. 7)

**Comment by deiruch** [comment]
War ein Stück weit auch Absicht, damit Leute nicht selbst formatieren. User sollten nur Absätze und Listen formatieren können.

**Comment by StephenRUK** [comment]
Ich dachte mir, dass da eine gewisse Absicht dahinter steckt. Listen mit '*' werden richtig formatiert. Möglicherweise sind nur alphabetische Listen betroffen, wie in diesem Beispiel mit a), b), c)

**Comment by deiruch** [comment]
Man könnte a),b),c) Listen erkennen oder einfach in "* "-Listen umschreiben.

**Comment by deiruch** [comment]
Evtl. müsste man das auch nur Dokumentieren? Dem User irgendwie klar machen...
