### ISSUE TITLE
Skipping on Chrome (macOS)

### ISSUE THREAD

**Issue by tamberg** [i4Ds/ProStudCreator#259]
The view to add new projects tends to "skip" / "jump" around when scrolling.

How to reproduce: open view below, scroll (I'm using the touch pad).

https://www.cs.technik.fhnw.ch/prostud/AddNewProject

This makes editing new projects quite painful.

I'm using Chrome on macOS 10.13.6.

**Comment by deiruch** [comment]
Duplicate of #216
