### ISSUE TITLE
Notenwarnung Cc an Verantwortliche

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#261]
Wenn Dozierende die Note nicht eingeben erhalten sie eine entsprechende Warn-Email. Nach etwa 2 Warn-Emails sollte die EMail auch an den Institutskoordinator geschickt werden damit dieser intervenieren kann. Ob es genau nach zwei Warn-Emails der Fall ist muss abgeklärt werden, die Noten sollten auf jeden Fall vor dem Drucken der Diplome beim Ausbildungssekretariat sein (d.h. vielleicht macht im August auch bereits eine frühere Information des Projektkoordinators Sinn).

**Comment by Beckicious** [comment]
Erste umsetzung in 869ed2aab2008d55a5f5bd686e933ca6a1a046a4

**Comment by persillie** [comment]
Verwandt mit issue #275

**Comment by dgruntz** [comment]
Ist realisiert, d.h. Emails werden verschickt.
