### ISSUE TITLE
Duplikate

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#264]
Beim Projekt

    https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=2682

ist in der Datenbank eine Inkonsistenz vorhanden, denn immer wenn ich an diesem Projekt eine Änderung vornehme, dann wird es unter neuer ID abgespeichert (dupliziert).

Dieses Projekt ist wie folgt entstanden:

1) Projket ist im HS18 publiziert und gewählt worden.
2) Student musste das Projekt aus Krankheitsgründen abbrechen, wird aber im kommenden Semester wieder darauf arbeiten.
3) Ich habe das Projekt daraufhin aus dem HS18 zurückgezogen (am 28.11.18)
4) Ich habe das Projekt für den Studierenden Valentino Rugolo reserviert
5) Ich habe das Projekt für das FS19 eingereicht und publiziert.

Das Problem kann reproduziert werden in dem das Projekt über https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=2682 editiert wird (z.B. Hinzufügen einer Bemerkung) und dann gespeichert wird. Das Projekt ist dann dupliziert.

Ich vermute dass in der Datenbank bei diesem Projekt noch ein Eintrag vorliegt der da nicht sein sollte.

**Comment by Beckicious** [comment]
Wie vermutet waren die Einträge in der Datenbank nicht korrekt.
Ich habe diese nun korrigiert.
Jetzt sollte das Projekt nicht mehr dupliziert werden.

**Comment by dgruntz** [comment]
Trotzdem: Der Prozess oben beschreibt wie diese Inkonsistenz hergestellt werden konnte, d.h. mit deser Beschreibung kann vielleicht auch der Fehler behoben werden.

**Comment by dgruntz** [comment]
Problem sollte behoben sein da Projekte nicht mehr zurückgezogen werden können wenn sie laufen sondern nur abgebrochen. Und beim Abbrechen eines Projektes wird das Semester zurückgesetzt.
