### ISSUE TITLE
Anzeige Vorgängerprojekt

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#266]
Das Projekt

https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=2800

ist eine Weiterführung eines IP5-Projektes. Ich wollte das in ProStud erfassen, aber das Vorgängerprojekt wird gar nicht angezeigt. Es wird nur eine sehr kleine Liste von Projekten in dieser Liste angezeigt:

![image](https://user-images.githubusercontent.com/1516800/49598846-d1c03e80-f97f-11e8-8061-d7c445ccfd57.png)

Sollten da nicht alle im Vorsemester durchgeführten IP5-Projekte erscheinen?
Wenn eingeschränkt, dann allenfalls auf jene Projekte welche denselben Betreuern (oder demselben Hauptbetreuer) zugeordnet sind.

**Comment by Beckicious** [comment]
Das Feld Vorgängerprojekt ist spezifisch für IP5 Projekte, die auf IP6 verlängert werden. Dabei werden die selben Studenten wieder dem Projekt zugeordnet.
- Vielleicht sollte das Feld umbenennt werden.

**Comment by Beckicious** [comment]
Bedingungen damit ein Projekt in der Liste erscheint:
- Muss IP5 sein
- Muss Published sein
- Muss vom letzten Semester sein
- Muss als langes Projekt gekennzeichnet sein

Aktuell muss die Dauer des Projektes manuell in der Datenbank gesetzt werden, dass es in der Liste auftaucht.

**Comment by dgruntz** [comment]
Die Bedingung, dass es als langes Projekt gekennzeichnet sein muss ist falsch. Alle IP5-Projekte können als IP6 weitergeführt werden. Aufgelistet werden sollten also Projekte, die
- IP5 sind
- published
- letztes Semester
