### ISSUE TITLE
Warnen bei Weg-Navigieren ohne Speichern

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#27]
Michael Kalt hat schon Text verloren, wegen unabsichtlicher Navigation. Evtl. Nachfragen bei Änderungen, ob man die Seite wirklich verlassen will?

**Comment by deiruch** [comment]
Die Nachricht sollte beim Projekt-Ablehnen *nicht* erscheinen. (Dann wird nämlich auch weg-navigiert, ohne zu speichern)

**Comment by StephenRUK** [comment]
Du meinst wohl beim 2. Schritt des Ablehnens - diesen Button habe ich tatsächlich übersehen. Wird im nächsten Commit gleich behoben
