### ISSUE TITLE
Email Hinweis auf Ablauf der Frist für Thesistitel

### ISSUE THREAD

**Issue by persillie** [i4Ds/ProStudCreator#272]
Gemäss Angaben in ProStud können die Thesistitel bis 11 Wochen noch geändert werden. Um Nachfragen zu verhindern, könnte man folgenden Workflow implementieren:

13 Wo Thesisabgabe: Friendly Emailreminder an alle BetreuerInnen von IP6 Projekten, dass man noch 2 Wochen Zeit hat, den Thesistitel anzupassen

10,5 Wo vor Thesisabgabe: Friendly Reminder, dass in 2 Tagen die def. Thesistitel an admin.technik@fhnw.ch verschickt werden

10 Wo vor Thesisabgabe: Die Thesistitel werden im gewünschten Format automatisch an admin.technik@fhnw.ch verschickt. 

Die genauen Daten der Reminder/Verschicken muss natürlich mit Sandra oder wer immer hinter admin.technik@fhnw.ch sitzt, geklärt werden.

**Comment by Beckicious** [comment]
> 10,5 Wo vor Thesisabgabe: Friendly Reminder, dass in 2 Tagen die def. Thesistitel an [admin.technik@fhnw.ch](mailto:admin.technik@fhnw.ch) verschickt werden
Das wäre ja nach der Frist, oder war hier 11.5 Wo gemeint?

**Comment by persillie** [comment]
Nein, kurz nach der Frist, Markus hat gemeint, die 2 Tage könne man ihnen geben. Aber ehrlich gesagt, muss man das mit Sandra von der Admin klären. Das war mehr ein Vorschlag um solche Dinge wie letzten Di zu vermeiden.

**Comment by persillie** [comment]
Hallo Simon

ist das nicht implementiert? noch nicht ganz automatisch, aber das ist ja auch ok. Oder wie sieht es da aus?

**Comment by Beckicious** [comment]
wurde vor einiger Zeit umgesetzt
