### ISSUE TITLE
Mail zur Notenabgabe verschicken

### ISSUE THREAD

**Issue by Beckicious** [i4Ds/ProStudCreator#275]
- Notenabgabe Datum in Datenbank aufnehmen
- Notenabgabe Datum in Termine darstellen
- Reminder Mail für Notenabgabe Datum versenden

**Comment by persillie** [comment]
Bei diesem Email kann man auch den Hinweis auf das Abfüllen des Verrechnungsstatus machen, das sollte mit der Noteneingabe gemacht werden, dann kann man es ja auch beurteilen! 
Dann muss man dem nicht mehr extra nachrennen.

**Comment by Beckicious** [comment]
Dies wurden in #273 umgesetzt. Die Felder "Durchführungssprache", "Websummary" und "Verrechnungsstatus" müssen ausgefüllt sein um die Noten eintragen zu können.

**Comment by persillie** [comment]
Super danke

**Comment by Beckicious** [comment]
implemented in 12ee4c5a44986b767ec8972809bb022db181d367
