### ISSUE TITLE
Export automaticPayout

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#279]
Es gibt experten, welche Rechnung stellen, d.h. bei diesen Experten muss keine Entschädigung über das Ausbildungssekretariat ausgelöst werden.  In der Datenbank ist dies im Flab `automaticPayout` bei den Experten gespeichert.

Könnte dieses Flag auch beim Excel-Export exportiert werden?

Dort ist aktuell (in Kolonne W) nur das Flag `Experte   Bezahlt` aufgelistet.

**Comment by Beckicious** [comment]
Ist es möglich die neue Kolonne "Automatische Auszahlung" direkt zwischen den Kolonnen 'Experte Bezahlt' und 'Verteidigung-Datum' einzufügen, oder soll sie am Ende angefügt werden?

**Comment by dgruntz** [comment]
Ich würde sie genau dort einfügen wo Du vorgeschlagen hast. Es gibt ja kein Programm welches dieses Excel ausliest, daher ist es egal wo neue Kolonnen eingefügt werden.

**Comment by Beckicious** [comment]
closed with f1486af230fdd136e9450e160d9ae256a53da833
