### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#28]
Autosave wäre praktisch - ich habe schon Text verloren, weil mein doofer Browser etwas unstabil ist. Damit das funktioniert, müsste m.E. aber ebenfalls eine Revisions-History (Issue #6 ) der Projekttexte implementiert werden.

**Comment by dgruntz** [comment]
Umgekehrt: Falls ich etwas explizit nicht speichern will und die Seite einfach schliesse oder offen stehen lasse, dann wird der Text automatisch gespeichert. Wie bekommt man diese Version dann wieder weg?
