### ISSUE TITLE
413 Request Entity Too Large Error

### ISSUE THREAD

**Issue by Beckicious** [i4Ds/ProStudCreator#285]
Error `413 Request Entity Too Large` gets thrown when the picture is to large and all inputs will be lost.
Steps to take:
- Make sure the inputs are not lost
- Find and fix the cause of the error
- Same reason as #281 ?

**Comment by dgruntz** [comment]
Original error report from Christoph Stamm:

> Habe gestern schon zweimal das Webformular ausgefüllt. Weil mein Bild aber zu gross war, 
> kam am Schluss beim Speichern eine Fehlermeldung und der ganze Eintrag war verloren. 
> Der Back Button funktioniert dann auch nicht.  
> 
> Verbesserungsvorschlag fürs Tool: Daten zuerst speichern und dann Fehlermeldung generieren. 
> Gruss 
> Christoph

**Comment by dgruntz** [comment]
Spezifisches Problem war ein Problem auf dem Proxy, d.h. die Daten sind auf dem Server nicht angekommen und können auch nicht vorab gespeichert werden.

Lösung für Nutzer: Zuerst Daten hochladen und dann das Bild in einem zweiten Schritt hinzufügen ;-)
