### ISSUE TITLE
Excel Export

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#287]
Beim Export der Projekte (Admin => Export) werden in den Kolonnen GHI un JKL die Namen/Email-Adresse/Note der beiden Studierenden aufgelistet.

Damit diese Liste gerade für die Bereitstellung der Daten für die Ausstellungsbroschüre verwendet werden kann wäre es sinnvoll, wenn die Namen der beiden Studierenden alphabetisch sortiert wäre, also z.B. bei den Studierenden "Renato Rao" und "Dominik   Sommerhalder" zuerst Herr Rao.

Ich überlasse es dem Implementierer ob die Reihenfolge erst beim Erzeugen des Excel festgelegt werden soll oder bereits beim Speichern der Daten.

**Comment by Beckicious** [comment]
Alphabetisch sortiert nach Nachname wenn ich das richtig verstehe?

**Comment by dgruntz** [comment]
Ja, das war die Idee (also Rao vor Sommerhalder).

**Comment by Beckicious** [comment]
implemented in 742750b6cfca0c1f57ecb482c3ad819f6d72d391
