### ISSUE TITLE
Excel - Bewertungsbogen: Boni werden nicht automatisch zugerechnet.

### ISSUE THREAD

**Issue by Aadjou** [i4Ds/ProStudCreator#288]
Im neuen Bewertungsbogen werden die Boni nicht mehr automatisch an die Gesamtnote angerechnet. Ausserdem enthält die Vorlage bereits Bewertungen und Kommentare.

Die Gewichtung 2.1 und 2.2 ergibt im Block nicht mehr 2, sondern 3. Da ist nicht ganz klar, ob nun die Beschreibung oder die Vorlage geändert werden soll.

https://github.com/i4Ds/ProStudCreator/blob/master/ProStudCreator/Content/Bewertungsbogen%20Projekte%205%20und%206.xlsx

**Comment by dgruntz** [comment]
Der Bewertungsbogen ist nicht unter unserer Kontrolle sondern gilt für die ganze Hochschule, d.h. wenn man hier etwas ändern will dann muss man das über Martin Meyer machen.

Die aktuellste Version des Bewertungsbogens liegt jeweils auf dem AD unter
T:\A1811_HT_Infos\A1811_Infos\Studienbetrieb\Projektschiene\Bewertung_Projekte_5_und_6

Leider werden Änderungen an den Dokumenten in diesem Verzeichnis nicht kommuniziert.

**Comment by Aadjou** [comment]
Danke für die Information.
