### ISSUE TITLE
Umlaute fehlen in manchen PDFs (?!?)

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#29]
Bei https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=45 fehlen im erstellten PDF im ersten Absatz die Umlaute. (z.B. Raume statt Räume, oder fur statt für)

**Comment by StephenRUK** [comment]
Konnte im PDF Creator keine Fehler nachweisen - der Text wird beim Debuggen genau so angezeigt mit Umlauten. Mit Test-projekten habe ich schlussendlich festgestellt, dass die Zeichen mit Umlaute in diesem Projekt (id 45) mit 2 ASCII Zeichen codiert wurden (also 'a' und ASCII 776 zusammen -> wird als ä angezeigt im Browser, Notepad usw, aber nicht im PDF).

"Quick fix": Die Zeichen durch 'richtige' öäü ersetzen
Richtiger "Fix": Diese Kombinationszeichen könnten ersetzt werden.

Die Frage ist nur, wieso genau diese Codierung zustande kam. Browser/OS abhängig?

**Comment by StephenRUK** [comment]
Betroffene Projekte müssen nochmals gespeichert werden, dann werden 2-Byte-Zeichen in 1-Byte-aquivalente Unicode Zeichen konvertiert. Stichwort: String.Normalize
