### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by Beckicious** [i4Ds/ProStudCreator#296]
![adfasdf](https://user-images.githubusercontent.com/14994259/70995954-0823b400-20d2-11ea-90bc-0db41f3e85ba.png)

Proxy <-> Server time out

**Comment by Beckicious** [comment]
Das generieren der PDF scheint sehr lange zu dauern.
Mögliche Ansätze:
- Bildgrösse limitieren bzw. effektiv überprüfen
- PDF Generator optimieren

**Comment by Beckicious** [comment]
![image](https://user-images.githubusercontent.com/14994259/71085020-d32d6500-2196-11ea-8e39-e4a7abc2eed3.png)

**Comment by Beckicious** [comment]
Mail von Bernhard:
```
ich habe mal eine Anpassung am Proxy vorgenommen.
Bitte weiter beobachten.
```

**Comment by Beckicious** [comment]
@dgruntz Hattest du noch weitere 504 Meldungen seit Bernhard etwas angepasst hat?

**Comment by dgruntz** [comment]
Nein, das Exportieren des PDFs mit allen Projekten hat im 2020 ohne Probleme funktioniert, und das PDF ist ja immer grösser geworden. Aus meiner Sicht kann dieses Issue geschlossen werden.
