### ISSUE TITLE
Noten Export

### ISSUE THREAD

**Issue by Beckicious** [i4Ds/ProStudCreator#300]
Idee von Dominik:

Wir erweitern die Admin Page um einen weiteren Button „Noten“ neben
![a](https://user-images.githubusercontent.com/14994259/74914575-f953c900-53c2-11ea-87d3-8fd0e4f43b1b.png)

wo man die Noten exportieren kann. Wir können ALLE Noten exportieren, da ja nur jene des entsprechenden Moduls geladen werden.
Die Daten:
- IDAnlass
- AnlassNummer
- AnlassBezeichnung

könnte man über die Web-Applikation in drei Feldern erfassen lassen. Ich würde einfach übernehmen was da drin steht, und wenn nichts drin steht wird einfach nichts übernommen. Dies ist jedoch nur nötig wenn Sandra diese Datei selber runterlädt. Sonst macht das auch keinen Sinn, dann könnte man die Felder einfach leer lassen und vielleicht gelb hinterlegen, damit man
dann dort die richtigen Werte eintragen kann.

Bei meinen Tests habe ich alles unnötige gelöscht, aber wenn man die Felder leer lässt wäre es ja sinnvoll, wenn man die Bezeichn ungen im Excel trotzdem ausgibt:

A | B
-- | --
IDAnlass | 9348724
AnlasssNummer | 0-19HS.T-B-X-0pro5I.SN/5Ibb
AnlassBezeichnung | Projekt 5 Informatik 19HS 5Ibb
Exportiert   am | 20.02.2020
Exportiert   durch | Gruntz   Dominik

Und bei Exportiert am / durch könnte man ja das Datum und entweder den Namen des Nutzers oder `PROSTUD` hinschreiben.

Das Excel muss die beiden Blätter
-	Konfig
-	NotenDefinitiv

enthalten.

Die Frage ist jetzt einfach ob wir bei den Studierenden bereits die EventoID gespeichert haben.

**Comment by dgruntz** [comment]
> Die EventoID wird nicht gespeichert. Es gibt auch keine Studenten Tabelle in der Datenbank bis jetzt.
> Alle Studentendaten (E-Mail, Name) werden momentan im Projekt Eintrag gespeichert.
> 

OK, aber man könnte bei den Prokekteinträgen neben Name/Vorname/Email auch noch die Evento-ID ablegen. Im File „Applications.xml“ das als Input für die Zuteilung verwendet wird sind diese Daten auf jeden Fall bereits drin.

Allenfalls muss die Evento-ID auch vom Optimierungsprogramm eingelesen werden, damit diese ID dann auch bei der generierten Datei (`Zuteilung.xlsx`) eingefügt werden kann.

**Comment by Beckicious** [comment]
@dgruntz 
Ich habe eine erste Version des Noten Excel Export für uns live gestellt.

Sind die Felder Vor- und Nachname relevant für den Upload?
Bisher sind Vor- und Nachname der Studierenden in einem Feld gespeichert worden, was die automatische Trennung bei Namen die aus mehr als zwei Wörtern bestehen schwierig macht.
In diesem Fall wäre es von Vorteil Vor- und Nachname in seperaten Feldern zu speichern.

**Comment by dgruntz** [comment]
Für den Upload sind folgende Felder relevant:
- IDPersopn
- Nachname
- Vorname
- Bewertung
- Bemerkung

![image](https://user-images.githubusercontent.com/1516800/75793244-5f4f3180-5d6f-11ea-8ee5-c45eda0f94bb.png)

Folglich brauchen wir (neu) Vor- und Nachname. Meine Datei `Students.xmlx` die ich exportiere enthält diese Daten, ich beziehe ich diese auch aus Evento und könnte sie auch in der einen Datei `Applications.xmlx` einfügen.

Ich habe das eben rasch ausprobiert und in einem Excel den Vornamen eines Studierenden geändert, und dann wird diese Note nicht mehr übernommen, ist als wirklich nötig.

**Comment by dgruntz** [comment]
@Beckicious, weisst Du gerade warum beim generierte Notenfile kein Filter gesetzt werden kann?
Habs rausgefunden: Die Sheets sind gruppiert (daher erscheint im Titel auch [Group]). Diese Gruppierung sollte entfernt werden.

**Comment by dgruntz** [comment]
Habe die generierte Datei eben eingelesen, und ich erhalte folgende Meldung:

    Das Excel kann nicht verarbeitet werden (Format oder Inhalt entspricht nicht den Erwartungen)	

Der Grund könnte sein, dass das Konfig-Sheet nicht mehr richtig war, und das lag daran dass da eine Gruppierung zwischen diesen beiden Sheets vorhaden war, d.h. mit dem Setzen der Felder B1-B3 wurden auch die entsprechenden Felder im `Konfig` Sheet geändert!

**Comment by Beckicious** [comment]
Die Gruppierung ist nun entfernt und den Filter habe ich auch gleich eingebaut.

**Comment by dgruntz** [comment]
Ich habe jetzt eine neue Fehlermeldung:

	Excel (19HS_Noten_Excel_Test.xlsx) stimmt nicht mit aktuellem Anlass überein

aber ich sehe nicht warum. Habe das für 2 Studierende ausprobiert und dort die `EventoID` eingetragen.

**Comment by Beckicious** [comment]
Ich habe die Eingabefelder für die Studierenden in der InfoPage mit einem EventoID Feld erweitert und die Namen in Vor- und Nachname aufgeteilt. Die Datenbank ist auch entsprechend aktualisiert.

![image](https://user-images.githubusercontent.com/14994259/75991290-90a63980-5ef6-11ea-9061-b5e735cfe083.png)

**Comment by dgruntz** [comment]
> Die Datenbank ist auch entsprechend aktualisiert.

Ich habe das jetzt so verstanden dass in der DB diese Felder vorhanden sind. 
Wirst Du noch die Evento-IDs für das HS19/20 in die DB einlesen? 
Und braucht es (für die Zukunft) noch eine Änderung bei den zu importierenden Daten (`Applications.xmlx`)?

**Comment by Beckicious** [comment]
> Ich habe das jetzt so verstanden dass in der DB diese Felder vorhanden sind.

Ja genau, und die bestehenden Namen von Studierenden sind aufgeteilt worden.

> Wirst Du noch die Evento-IDs für das HS19/20 in die DB einlesen?

Ja

> Und braucht es (für die Zukunft) noch eine Änderung bei den zu importierenden Daten (Applications.xmlx)?

Die Vor- und Nachnamen beim "Bewerbungen" Blatt analog zum "Studierenden ohne Bewerbungen" Blatt, damit ich die Namen direkt einlesen kann.

**Comment by dgruntz** [comment]
https://gitlab.fhnw.ch/dominik.gruntz/proapp/issues/62

**Comment by dgruntz** [comment]
Gemäss Info von Kai Moosmann müssen die Felder über den *Name Manager* definiert werden. Für das Noten-Excel braucht es folgende Einträge:

Feldname | Referenz
-----------|-----------
_FHNW_ID_					| =Konfig!$B$1
_FHNW_FIELD_Notenskala		| =Konfig!$B$2
_FHNW_COLUMN_Noten		| =Konfig!$B$3
_FHNW_FIELD_AnlassID			| =NotenDefinitiv!$B$1
_FHNW_FIELD_AnlassNummer	| =NotenDefinitiv!$B$2
_FHNW_FIELD_Bezeichnung		| =NotenDefinitiv!$B$3
_FHNW_TABLE_Bewergung		| =NotenDefinitiv!$A$8:$J$N

Mit diesen Definitionen kannd as Exel hochgeladen werden. Tabellennamen und die genaue Position der Zellen spielen keine Rolle!

**Comment by Beckicious** [comment]
Ich habe die Felder hinzugefügt.
"_FilterDatabase" habe ich auch noch dazugenommen mit Referenz "=NotenDefinitiv!$A$7:$G$7".

**Comment by dgruntz** [comment]
Ich habe es eben ausprobiert, und es funktioniert. Ich brauche das Excel nicht mal zu filtern, ich kann einfach das ganze hochladen, Für jene Studierende die nicht angemeldet sind erhält man die Meldung

    Speichern der Bewertung fehlgeschlagen: Person 951205 hat keinen OK Status 
    oder ist nicht angemeldet.

aber das stört mich nicht. Im Log steht dann (beim IP5 das ich eben ausprobiert habe) die Meldung

    Es wurden 4 Bewertungen erfolgreich gesetzt.

Ich denke, damit können wir dieses Issue schliessen.
