### ISSUE TITLE
Projektverrechnung: Feld für Verrechnungsnummer/Auftragsnummer einfügen

### ISSUE THREAD

**Issue by persillie** [i4Ds/ProStudCreator#301]
Bei gewissen Firmen (SBB, Siemens etc.) ist es wichtig, dass wir eine Referenznummer auf der Rechnung ausweisen können. 

Diese Information kommt normalerweise zu den BetreuerInnen (oder ganz am Schluss des Rechnungsprozesses, weil die Rechnung zurückgewiesen wird). 

Da die Rechnungsinformationen aus ProStud zusammenerstellt werden, sollte es ein optionales Feld Verrechnungsnummer geben, wo die BetreuerInnen diese Information eintragen können. Das sollte natürlich exportiert werden, damit die Admin das auch auf die Rechnung übertragen können.

**Comment by dgruntz** [comment]
Bei den Kundendaten wird bereits jetzt eine Referenznummer erfasst. 

![image](https://user-images.githubusercontent.com/1516800/75985933-6f8d1b00-5eed-11ea-9306-1354000b7e89.png)

Ist das nicht die Information die Du Dir wünscht? Fehlt allenfalls nur noch der Export dieses Feldes?

**Comment by dgruntz** [comment]
> Doch, sorry, ich habe kein neues Projekt erfasst (zu erfassen versucht) sondern nur das SBB Projekt geöffnet und kein Feld gesehen. Das Feld reicht, vielleicht muss man besser erklären was es beinhalten soll, mind. Kathrin ist jetzt nicht von alleine darauf gekommen, die Nummer dort einzutragen sondern schickt sie Hanny etc. 

dann genügt es, das Feld "Referenz des Kunden" in "Verrechnungs-/Auftragsnummer" umzuändern.

Diese Nummer wird aber noch nicht exportiert, d.h. das wäre die Änderung die nötig ist, damit dieses Issue als erledigt markiert werden kann.

**Comment by Beckicious** [comment]
Im Export-Excel wird diese Nummer momentan als "Kunden-Referenznummer" exportiert. Soll sie im Verrechnungs-Excel auch so (mit geänderter Bezeichnung) exportiert werden?

**Comment by dgruntz** [comment]
Im Export-Excel kannst Du es so lassen wie es ist, denn das ist ja nur für uns.
Aber im Verrechnungs-Excel ist diese Referenz nicht vorhahden, dort würde ich sie dann auch gerade Verrechnungs-/Auftragsnummer nennen, wie auf der Maske.

**Comment by Beckicious** [comment]
Die Felder sind umbenennt und die Spalte im Verrechnungs-Excel ist hinzugefügt.
