### ISSUE TITLE
WebSummary Link

### ISSUE THREAD

**Issue by Beckicious** [i4Ds/ProStudCreator#305]
Der Link zum WebSummary ist nicht immer korrekt.
Momentan wird der Link abhängig vom Semester des Projektes gebildet.
- 19HS_I4DSXX -> https://web.fhnw.ch/technik/projekte/i/bachelor19/
- 19HS_I4DSXX -> https://web.fhnw.ch/technik/projekte/i/ip519/

Wird der Link anhand des Abgabesemester/jahr erstellt?

**Comment by Beckicious** [comment]
Die WebSummary für 19HS und 20FS sind unter https://www.fhnw.ch/plattformen/bachelor20/ zu finden

@dgruntz Weisst du unter welchem Link die IP5 WebSummary zu finden sind?

**Comment by dgruntz** [comment]
Diese sind dieses Jahr unter
https://web0.fhnw.ch/ip520/
erreichbar. Weiss nicht ob es noch einen alias für diese URL gibt.

**Comment by koebel** [comment]
es wär sehr nützlich, wenn in Prostud automatisch die richtige URL beim Link zum Websummary generiert würde... bei den Projekten vom FS 20 wird ein Link gemäss dem Syntax, der anscheinend bis 2019 korrekt war, generiert...

**Comment by dgruntz** [comment]
Es wäre noch besser wenn wir hier stabile URLs hätten, d.h. wenn die Syntax nicht jedes Jahr ändert.

**Comment by dgruntz** [comment]
Hier tut sich etwas. Es wird voraussichtlich EIN Server geben auf dem alle Websummaries liegen. Sobald wir das haben kann dieses Problem gelöst werden.

**Comment by dgruntz** [comment]
Die Webseiten sind neu unter folgendem Link erreichbar:
https://web0.fhnw.ch/ht/informatik/ip5/21fs/
https://web0.fhnw.ch/ht/informatik/ip6/21fs/

d.h. die einzelnen Projekte unter
https://web0.fhnw.ch/ht/informatik/ip5/21fs/21fs_i4ds10/index.html
https://web0.fhnw.ch/ht/informatik/ip6/21fs/21fs_i4ds04/index.html

Die Struktur sieht also wie folgt aus:

     https://web0.fhnw.ch/<hochschule>/<sg>/<projektart>/<sem>/21fs_i4ds10/index.html

mit
- hochschule=ht
- sg=informatik
- projektart=ip5 oder ip6
- sem=2xfs oder 2xhs

Bemerkungen:
- Beim Projektverzeichnis haben wir uns entschieden, das Semesterkürzel nochmals voranzustellen.
- Alles Kleinbuchstaben
- `index.html` muss nicht angegeben werden.
- Der Prefix wird sich allenfalls noch ändern (also das https://web0.fhnw.ch)

Die Seiten für FS21 sind eingerichtet.

**Comment by Beckicious** [comment]
Ich habe den Link auf die von Dominik beschriebene Struktur umgestellt.

**Comment by dgruntz** [comment]
Damit ist dieses Issue gelöst.
