### ISSUE TITLE
Issues if project title contains a comma

### ISSUE THREAD

**Issue by koebel** [i4Ds/ProStudCreator#306]
If the project title contains a comma, it is not possible to export a PDF file of the project. In addition I also observed that in this case it is not possible to duplicate the project. The following error occurs:

Server Error in '/prostud' Application.
String or binary data would be truncated.
The statement has been terminated.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: String or binary data would be truncated.
The statement has been terminated.

Source Error:
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:
[SqlException (0x80131904): String or binary data would be truncated.
The statement has been terminated.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +3318656
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +334
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4289
   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) +514
   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) +3392
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) +725
   System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) +551
   System.Data.SqlClient.SqlCommand.ExecuteNonQuery() +391
   System.Data.Linq.SqlClient.SqlProvider.Execute(Expression query, QueryInfo queryInfo, IObjectReaderFactory factory, Object[] parentArgs, Object[] userArgs, ICompiledSubQuery[] subQueries, Object lastResult) +410
   System.Data.Linq.SqlClient.SqlProvider.ExecuteAll(Expression query, QueryInfo[] queryInfos, IObjectReaderFactory factory, Object[] userArguments, ICompiledSubQuery[] subQueries) +189
   System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query) +428
   System.Data.Linq.StandardChangeDirector.DynamicUpdate(TrackedObject item) +101
   System.Data.Linq.ChangeProcessor.SubmitChanges(ConflictMode failureMode) +811
   System.Data.Linq.DataContext.SubmitChanges(ConflictMode failureMode) +681
   ProStudCreator.ProjectExtensions.DuplicateProject(Project _p, ProStudentCreatorDBDataContext db) in C:\WORK\PROSTUD\ProStudCreator\ProStudCreator\ProjectExtensions.cs:94
   ProStudCreator.ProjectEditPage.DuplicateProject_Click(Object sender, EventArgs e) in C:\WORK\PROSTUD\ProStudCreator\ProStudCreator\ProjectEditPage.aspx.cs:1931
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +11594516
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +274
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1890

**Comment by Beckicious** [comment]
Thank you for reporting this issue.
Both issues should be fixed.

The problem with the PDF was that the filename string in the header was not quoted.

The source of the duplicate problem was the length of the name.
Normally when a project gets duplicated the string " (Duplikat)" gets added to the name.
In this case however it exceeded the maximum name length and thus crashed.
I removed the addition of the " (Duplikat)" string if that would lead to a name that is too long.
