### ISSUE TITLE
Vorgängerprojekte

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#308]
Bei der Wahl eines Vortgängerprojektes mit der Maske

![image](https://user-images.githubusercontent.com/1516800/82371995-6fe08100-9a1b-11ea-9a64-b723c942cb40.png)

werden nur die IP5-Projekte aus dem letzten Semester angezeigt (Vermutung), aber gerade bei BB-Studierenden kommt es vor, dass das IP5 aus lem letzten HS dann im kommenden HS fortgesetzt wird, d.h. es sollten die IP5-Projekte der letzten beiden Semester dargestellt werden oder, falls man das einschränken möchte, dann des letzten Semesters und allenfalls des Vorsemesters, falls dieses ein HS war.

**Comment by Beckicious** [comment]
Momentan werden alle P5 des letzten Semesters und die langen P5 des vorletzten Semesters aufgelistet.
Sollen die kurzen P5 des vorletzten Semesters auch aufgelisted werden?

**Comment by dgruntz** [comment]
Alles klar, habe nicht gesehen dass die beiden Studierenden Brodwolf/Andermatt VZ-Studierende sind. Das erklärt warum sie in dieser Liste nicht erschienen sind. Ich denke, die Fortsetzung eines Projektes nach einer Pause ist ein Sonderfall, und der kann ja auch so gelöst werden dass ich das dann eintragen. 

Es ist sinnvoll dass die Lang-Projekte aus dem vorletzten Semester erscheinen. Lassen wir es daher wie es ist!
