### ISSUE TITLE
some people missing in list of Haupt- and Nebenbetreuung on prostud

### ISSUE THREAD

**Issue by koebel** [i4Ds/ProStudCreator#309]
Hi there, there are a number of research assistants from IIT missing in the list of "Nebenbetreuung" of prostud who are supposed to be co-supervising students projects in the next semester. Could you please add
- Yves Simmen, yves.simmen@fhnw.ch
- Cédric Merz, cedric.merz@fhnw.ch
- Martin Lacayo, martin.lacayo@fhnw.ch
- Marco Burri, marco.burri@fhnw.ch
- Alexander Schneiter, alexander.schneiter@fhnw.ch

Also our new Computer Graphics Professor, who starts on June 1st should be added (to "Hauptbetreuung") because there are projects which he will be supervising in the next semester.
- Hilko Cords, hilko.cords@fhnw.ch

In addition, I noticed, that on the other hand our former apprentice, who is no more longer working for FHNW, is on this list. could you please remove
- Flavio Müller

Thanks for keeping the system up to date!

**Comment by koebel** [comment]
A little add-on: also Fiona Nüesch is no more longer working at IIT (since about 1 year :)

**Comment by Beckicious** [comment]
Thank you for the update. I have added/removed them from the lists.
