### ISSUE TITLE
Auflistungen mit a) b) c), 1) 2) 3) sollten auch erkannt werden

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#31]
Aktuell werden nur Auflistungen à la "- erster punkt, - zweiter punkt, ..." erkannt. Dasselbe sollte auch mit Auflistungen im Format "a) erster punkt, b) zweiter punkt, ..." funktionieren.

**Comment by StephenRUK** [comment]
Alphabetische und numerische Listen werden erkannt und ins PDF übernommen. Der Listenindex wird ebenfalls übernommen, um die Liste bei einem Texteinschub fortzuführen (Bsp: Projekt i4Ds07).

Produktive Webseite wurde nun aktualisiert.
