### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#311]
Falls sich jemand auf der Plattform anmeldet, der nicht berechtigt ist, dann wird er offenbar wieder an das Login weitergeleitet, und, da er sich bei AAI bereits angemeldet hat, wieder auf die Plattform weitergeleitet was zu einer Schleife (und einer Fehlermeldung ERR_TOO_MANY_REDIRECTS mit der Empfehlung, die Cookies zu löschen).

Besser wäre es den Benutzer zu informieren, dass er nicht berechtigt ist auf die Plattform zuzugreifen, vielleicht ergänzt durch eine Information die angibt an wen er sich melden muss falls er meint, dass er doch Zugriff haben sollte.

**Comment by Beckicious** [comment]
Personen, die nicht in der Datenbank eingetragen sind, sollten nun korrekt auf die "AccessDenied" Seite weitergeleitet werden. Dort werden Sie auch darauf hingewiesen, dass sie sich an mich wenden können um Zugang auf die Seite zu erhalten.
