### ISSUE TITLE
falsche Fehlermeldung

### ISSUE THREAD

**Issue by koebel** [i4Ds/ProStudCreator#315]
Die Fehlermeldung "Länge: Das PDF ist länger als eine Seite!" wird angezeigt, obschon der Content nur 1 Seite ist. Im PDF wird eine zweite, jedoch leere Seite generiert...

Es handelt sich um folgendes Projekt: https://www.cs.technik.fhnw.ch/prostud/ProjectEditPage?id=8033

**Comment by Beckicious** [comment]
fixed in 1cfe422188948e5fd6bd46b18d4625ec701f1bc2
