### ISSUE TITLE
Überlange PDFs können eingereicht werden

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#318]
https://www.cs.technik.fhnw.ch/prostud/PDF?dl=false&id=8259 ist länger als eine Seite und konnte eingereicht werden. Oder vielleicht auch eingereicht und dann noch verändert. Es sollten nur Projekte eingereicht werden können, die auf eine Seite passen.

**Comment by Beckicious** [comment]
In diesem Fall wurde das Projekt eingereicht und danach noch verändert.
Ich schlage vor, dass ich es so anpasse, dass eingereichte Projekte nicht mehr bearbeitet werden können.

**Comment by deiruch** [comment]
Solange Admins auch in diesem Status noch Edit-Rechte haben, wäre das eine gute Lösung.
