### ISSUE TITLE
Fehler wenn bei Raum ein zu langer String eingegeben wird

### ISSUE THREAD

**Issue by danielkroeni** [i4Ds/ProStudCreator#320]
Ich habe beim Raum einen MS Teams Link rein gemacht und beim abschliessen kam eine Fehlermeldung, dass ein String "truncated' würde. Ich habe dann den Back Button geklickt und meine eingetragenen Werte waren wieder verschwunden.

Ich würde für das Attribut Raum längere Strings erlauben in der DB und sicher das Textfeld im Frontend so begrenzen, dass keine längeren Strings eingegeben werden können als das Backend akzeptiert. Hier meine ursprüngliche Eingabe, die zum Fehler geführt hat:

Raum:  https://teams.microsoft.com/l/meetup-join/19%3ameeting_YzliNmM0YWYtNzdmZC00OWVmLTg0ZTktNzhiOTk5NWM0OTYx%40thread.v2/0?context=%7b%22Tid%22%3a%229d1a5fc8-321e-4101-ae63-530730711ac2%22%2c%22Oid%22%3a%2241181077-ab10-417f-b410-acce2beec432%22%7d

Danke und Gruss
Daniel

**Comment by Beckicious** [comment]
umgesetzt in bb235f7a039c6a23fca15bd6bb107168a2a5aee1

**Comment by danielkroeni** [comment]
Danke!

Beckicious ***@***.***> schrieb am Mo., 10. Mai 2021, 12:18:
