### ISSUE TITLE
SG DataScience extension

### ISSUE THREAD

**Issue by Beckicious** [i4Ds/ProStudCreator#321]
Extend projects to SG DataScience

- ProjectEditPage
  - [x] Add two checkboxes for `Projekt ausschreiben für Studierende im:`
    - `SG Informatik` & `SG Data Science`
    - both can be checked
  - [x] Add a new topic tag `Data Science`
- ProjectInfoPage
  - [x] Add Dropdown with SGs to set in which SG the project will be done
- Excel
  - [x] Add the new features

**Comment by Beckicious** [comment]
@dgruntz 
Lieber Dominik
Folgende Spalten würde ich dem "Informatikprojekte"-Excel hinzufügen:
- SubmitToStudyCourseCS
- SubmitToStudyCourseDS
- TypeDataScience

Wo bzw. in welchen Spalten wäre es für dich am einfachsten für den ProApp import?

Mein Vorschlag wäre die beiden Submit zwischen den Sprachen und den Types und der neue Type am Ende einzufügen.

**Comment by dgruntz** [comment]
Lieber Simon,
Ich wollte eben ProApp anpassen, aber wenn ich das richtig sehe hast Du die Anpassung noch nicht vorgenommen, oder?

Ich habe nur die Spalte `TypeDataScience` gesehen. Ich weiss nicht ob ich im GUI diese Spalte noch einführen kann. Wenn nicht, ist das auch nicht s schlimm, denn alle Projekte in der Kategorie `TypeDataScience` haben auch den Tag `TypeMlAlg` gesetzt, d.h. ich frage mich gerade ob es diesen zweiten Tag noch braucht wenn es dann ja auch noch die Unterscheidung nach Studiengang gibt.

Wenn ich Proapp anpasse (auf HS) dann werden den DS-Studierenden nur jene Projekte angezeigt, die auch für DS-Studierende ausgeschrieben sind. Als Variante könnte man auch das Label `TypeMLAlg` in `TypeMLAlgDS` umbenennen.

Aus meiner Sicht pressiert es nicht da jetzt am kommenden Montag die DS-Studierenden noch keinen Zugriff auf ProApp haben.

**Comment by Beckicious** [comment]
Ich habe das `Projektliste in Excel` Excel angepasst. Nun sind wieder alle Projekte enthalten mit den zwei zusätzlichen Spalten `SubmitToStudyCourseCS` und `SubmitToStudyCourseDS`.
