### ISSUE TITLE
Default Sorting auf AdminPage

### ISSUE THREAD

**Issue by lunactic** [i4Ds/ProStudCreator#322]
Wäre es evtl. möglich, das Deafault Sorting auf der Admin Page bei "Projekte in Bearbeitung" auf absteigendes Datum zu setzen? So würde man schnell auf einen Blick die neuen Projekte zuerst sehen und nicht alle die alten von 2015 .

**Comment by dgruntz** [comment]
Finde ich eine sinnvolle Änderung. Ich kehre auch immer als erstes die Sortierreihenfolge wenn ich diese Seite öffne.
