### ISSUE TITLE
Termine (ext)

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#324]
Unter [https://www.cs.technik.fhnw.ch/prostud/ext/Termine](https://www.cs.technik.fhnw.ch/prostud/ext/Termine) sind in der letzten Kolonne keine Daten mehr aufgeführt:

![image](https://user-images.githubusercontent.com/1516800/119654843-29411600-be29-11eb-84bc-91b231963b7d.png)

Ich denke, die sind einfach nicht mehr erfasst.

**Comment by dgruntz** [comment]
Jetzt fehlen nur noch die (externen) Termine für

- Info Veranstaltung 
- Anmeldung ProApp

und die (internen) Termine

- Notenabgabe IP5
- Notenabgabe IP5 (Lang) / IP6

**Comment by dgruntz** [comment]
**Daten 22HS:**

Info Veranstaltung: **Montag, 13.06.2022**
(Das ist die letzte Unterrichtswoche, und am Montag davor ist Pfingstmontag)

Anmeldung ProApp: **Freitag, 01.07.2022**

Notenabgabe IP5: **Freitag, 17.02.2023, 12:00 Uhr**
Das ist immer der Freitag in KW07

Notenabgabe IP5 (Lang) / IP6: **Freitag, 24.03.2022**

**Comment by Beckicious** [comment]
Ich habe die Daten ergänzt bis auf die Notenabgabe IP5 (Lang) / IP6, dieses scheint nicht zu stimmen. Bisher war es immer um den 1. Mai.

**Comment by dgruntz** [comment]
oops, ja ich glaube da habe ich die Abgabe der Arbeit erwischt (und nicht die Abgabe der Noten). Werde ich anschauen.

**Comment by dgruntz** [comment]
Die Noten für die P6-Projekte (und IP5-Lang) snd spätestens nach der Verteidigungswoche verfügbar. Im nächsten Jahr finden die Verteidigungen vom 18.04. bis 29.04 statt. Als Deadline hast Du Sonntag, 01.05.2022 eingetragen. Die Deadline vom Ausbildungssekretariat ist dann sicher 2.05. 12:00 Uhr, aber der 01.05. passt somit.

Für HS22 gilt, dass die Verteidigungen vom 17.04. bis 28.04.2023 stattfinden. Folglich ist die Deadline für die Notenabgabe der **Sonntag, 30.04.2023**.
