### ISSUE TITLE
Hinweis zur Verrechenbarkeit

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#331]
Diesen Hinweis verstehe ich nicht:

![image](https://user-images.githubusercontent.com/1516800/132521134-4279404d-5fa4-4f89-a2ca-c475b05506a4.png)

Ist es nicht so, dass auch diese Information erst dann in die entsprechenden Excel-Files exportiert werden wenn das Projekt abgeschlossen wird? Oder kann es sein, dass eine Verrechnung bereits vorab ausgelöst wird?

Ich hätte jetzt erwartet dass mit dem Abschliessen des Projektes auch erst dieser Verrecnungsstatus exportierbar wird.

**Comment by Beckicious** [comment]
Ja das stimmt. Ich nehme den Hinweis raus.
