### ISSUE TITLE
new Project Supervisors

### ISSUE THREAD

**Issue by koebel** [i4Ds/ProStudCreator#336]
Please add these people as co-supervisors (Nebenbetreuung) to ProStud:
- Nitish Patkar, nitish.patkar@fhnw.ch
- Alexander Legath, alexander.legath@fhnw.ch

Thanks!

**Comment by Beckicious** [comment]
They are added.

**Comment by koebel** [comment]
Thanks!

**Comment by koebel** [comment]
Sorry to bother again, would you mind to add Alain too?
Alain Zanchetta, alain.zanchetta@fhnw.ch

**Comment by Beckicious** [comment]
Added as well
