### ISSUE TITLE
"Auftraggeber" ist (k)ein Pflichtfeld bei FHNW-internen Projekten

### ISSUE THREAD

**Issue by sfiruch** [i4Ds/ProStudCreator#341]
Auch bei FHNW-internen Projekten erscheint auf der Infoseite ein Feld "Auftraggeber *", wobei das * für "Pflichtfeld" steht:
![image](https://user-images.githubusercontent.com/4119188/190664172-d887a1c1-866d-4ded-b677-c908835c1895.png)

Abschliessen kann man das Projekt dann aber trotzdem, obwohl nichts im Feld eingetragen wurde.

M.E. dürfte das Feld bei FHNW-internen Projekten gar nicht erscheinen.

**Comment by Beckicious** [comment]
Im Issue #329 wurde vorgeschlagen, dass das Feld bei internen Projekten auch angezeigt wird.  
Dass der Stern auch in diesem Fall (Intern -> kein Pflichtfeld) angezeigt wird, ist ein Fehler.

**Comment by SyleKu** [comment]
@deiruch 
Ist dieses Problem noch offen oder schon gefixed? Close issue or not?

**Comment by dgruntz** [comment]
Dieses Problem ist behoben, d.h. das Feld "Unternehmen" wird bei FHNW-internen Projekten angezeigt, aber es ist kein Pflichtfeld mehr.
