### ISSUE TITLE
Experte bezahlt

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#347]
Ich habe im generierten Excel gesehen, dass es für die Experten eine Kolonne "Experte bezahlt" gibt:

![image](https://user-images.githubusercontent.com/1516800/236404590-deebee72-fee4-48a6-b7fc-14a0db8361b0.png)

Wie kann dieses Flag gesetzt werden, d.h. gibt es dazu ein GUI? Oder wer/wie setzt sieses Flag aktuell?

**Comment by deiruch** [comment]
Es gibt einen Task der regelmässige, automatische Mails an die Administration zur Experten-Vergütung schickt. Das wurde irgendwann einmal in `new_SendPayExperts` neu implementiert, diese Funktion setzt das Flag aber anscheinend nicht mehr:
https://github.com/i4Ds/ProStudCreator/blob/b2f23dc42be05f253aa5cb0ebcac7d89d1254028/ProStudCreator/TaskHandler.cs#L1156-L1173

Den Grund für die Neuimplementation oder das Fehlen des Flag-Setzens kenne ich leider nicht. Vielleicht wissen @SyleKu oder @Beckicious mehr?

**Comment by dgruntz** [comment]
Besten Dank für die Erklärung.

Ich frage, weil wir uns überlegen, die Verrechnung der Experten an Daria zu übergeben, Sie ist die neue Assistentin von Christoph und Barbara (also der Leitung SGI).

In diesem Kontext habe ich folgende Fragen:

- Wie wurde das Flag gesetzt? Direkt in der DB?
- Wer hat bis jetzt die Liste an die Administration geschickt (damit die Zahlung ausgelöst wird)?

Diese Fragen können vielleicht von @SyleKu oder von @Beckicious beantwortet werden.

**Comment by Beckicious** [comment]
Wenn ich mich richtig erinnere, war der Grund für die Neuimplementation, dass Hanny sich wünschte nur noch ein Experten-Mail pro Semester zu erhalten.

Die Liste wird automatisch and den WebAdmin gesendet. Ich habe jeweils die Liste angeschaut und dann an Hanny und Hanna gesendet.

**Comment by dgruntz** [comment]
Alles klar, danke für die Klärung.
