### ISSUE TITLE
PDF Generator

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#350]
Wenn ein Projekt zugeteilt wird, dann wird beim generieren automatisch der Text "Dieses Projekt ist reserviert für XXXX" eingeblendet, aber der Abstand zwischen dem Titel "Bemerkung" und dem roten Text ist zu gross; man hat dann auf dem A4 nicht mehr genügend Platz für die eigentliche Beschreibung.

![image](https://github.com/i4Ds/ProStudCreator/assets/1516800/20047431-8293-4ba2-bc02-06270feacbdd)

Kann sein, dass der Abstand sinnvoll ist falls auf dem Flyer Bemerkungen erfasst werden, aber wenn die Section "Bemerkungen" leer ist, dann sollte diese rote Bemerkung direkt unter dem Titel stehen.

**Comment by dgruntz** [comment]
Ein Beispiel wo mir das eben aufgefallen is ist folgendes Projekt:
https://www.cs.technik.fhnw.ch/prostud/PDF?dl=false&id=13414

**Comment by SyleKu** [comment]
@dgruntz 
Ich habe soeben diesen Bug gefixed, der Grund war wirklich das eine zu grosse Space zusätzlich hinzugefügt wird.

**Comment by dgruntz** [comment]
Super, besten Dank!
