### ISSUE TITLE
Auswahl Vorgängerprojekt

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#357]
Ich wollte eben ein Projekt als Nachfolgeprojekt erfassen, aber es werden nicht alle abgeschlossenen Vorgängerprojekte angezeigt, aktuell bei mir nur zwei Projekte:

![image](https://github.com/i4Ds/ProStudCreator/assets/1516800/2fadf09c-bbd6-4db3-b323-1f31e592fa43)

Mir ist nicht klar, warum diese zwei Projekte angezeigt werden, und warum nur diese. Ich hätte erwartet, dass laufende oder abgeschlossene P5-Projekte angezeigt werden die max n Semester zurück liegen. In obiger Liste erscheinen jedoch nur zwei Projekte, und beide sind nicht von mir.

Bei berufsbegleitenden Studierenden kann es gut sein, dass diese 1-2 Semester aussetzen. Konret geht es bei mir um ein Projekt, das im FS23 durchgeführt wurde und das jetzt im HS24 forgesetzt wird.

**Comment by dgruntz** [comment]
Das Problem scheint teilweise behoben zu sein. Es kann gut sein, dass die Vortängerprojekte nicht angezeigt wurden da die Daten in der DB nicht (oder nicht vollständig) erfasst waren. Jetzt erscheinen folgende Daten:

![image](https://github.com/i4Ds/ProStudCreator/assets/1516800/37733cec-9a9d-49ec-b910-216c457d2005)

aber es erscheinen noch nicht alle P5-Projekte. Welche Projekte werden als Vorgängerprojekte angezeigt?
Allenfalls muss diese Selektion angepasst werden, d.h. es dürfen nicht nur die im vorhergehenden Semester durchgeführten Projekte angezeigt werden.

**Comment by Delberin-Ali** [comment]
@dgruntz Currently, the last and penultimate semester projects are considered "Vorgängerprojekte". (only the IP5 )
is that correct?

**Comment by dgruntz** [comment]
Have you a reference in the code?

I cannot answer what is correct, and obviously not all projects from the past can be listed, but I would say that your definition makes sense. If a project is defined today (in FS24) for HS24, then the projects from the current semester (FS24) and the last semester (HS23/24) should be listed. The latter is necessary for those students which study part time, because if a project is done in the autumn semester the followup project can only be done in the next autumn semester.

**Comment by dgruntz** [comment]
Thanks, @Delberin-Ali, the selection is defined in method `FillDropPreviousProject`:

https://github.com/i4Ds/ProStudCreator/blob/c126c35f7129c2bbd20d66fe768cc09c7bbb414b/ProStudCreator/ProjectEditPage.aspx.cs#L295

**Comment by dgruntz** [comment]
The definition is correct, and even stronger than mentioned above, i.e. project must be continued consecutively, and a semester might only be skipped if the predecessor project is defined as a parttype project (i.e. `FillDropPreviousProject`). 

The reason for the original problem might be problems with entering the data (i.e. the currently run projects). In the HS23 only two projects were long running projects:

![image](https://github.com/i4Ds/ProStudCreator/assets/1516800/735f8b5a-21a4-4c39-8f5b-d48c90258d97)

Based on this analysis I will close this issue.
