### ISSUE TITLE
Referenz auf Webauftritt

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#358]
Ich habe heute von Leticia folgende EMail erhalten:

> Dear Dominik,
> 
> We are finalising the P6 grading for one group of Data Science students. They have submitted their web summary under  (https://web0.fhnw.ch/ht/informatik/ip6/23hs/23hs_iit06/) but the ProStud link redirects here (https://web0.fhnw.ch/ht/datascience/ip6/23hs/23hs_iit06) and it marks the page as not found.
> 
> Could you please help us to solve this issue? because this is happening now the second or third time :(. They issue seems to occur each time we have data science students making their project at IIT. I'm not sure you are the right person, but perhaps you can point me out who can solve this issue? 
> 
> Thank you in advance!
> 
> Regards,
> Leticia

Offenbar verweist Prostud bei Data-Science Proejkten auf die URL https://web0.fhnw.ch/ht/datascience/ip6/`, d.h. auf eine Seite unterhalb des Studiengangs *datascience*. Diese Verzechnisse werden aktuell jedoch nicht erstellt, bzw. alle Projekte werden unterhalb von https://web0.fhnw.ch/ht/informatik/ip6/23hs/ bereitgestellt, und diese Seite trägt auch den Titel

**Hochschule für Technik
Studierendenprojekte in den Studiengängen Informatik/iCompetence/DataScience**

d.h. Du kannst im Code die Referenz auf "datascience" anpassen zu einer Referenz auf "informatik".

Wie das dann in Zukunft aussehen wird (wenn die HSI gegründet ist) ist noch offen.

**Comment by Delberin-Ali** [comment]
@dgruntz this is also done, right? should I close the issue?

**Comment by dgruntz** [comment]
Fixed by #359.
