### ISSUE TITLE
References to kushtrim.sylejmani

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#361]
Wenn eine EMail verschickt wird, dann steht im Footer die Referenz auf den Plattform-betreuer, und dieser Wert sollte von Kushtrim auf Delberin geändert werden.

![image](https://github.com/i4Ds/ProStudCreator/assets/1516800/455f775a-6e12-44e4-89f5-e55244eef4f4)

Die EMail-Adresse muss angepasst werden.

**Comment by Delberin-Ali** [comment]
Done
