### ISSUE TITLE
Teamgrösse "2er Team" wird mit NULL in Tabelle abgelegt

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#37]
Stattdessen sollte ID 3 abgelegt werden.

**Comment by StephenRUK** [comment]
War soweit nicht in der Lage diesen Fehler zu reproduzieren.
Getestet & erfolgreich:
- Neues Projekt erstellen, ohne Teamgrösse Dropdown zu ändern
- Neues Projekt erstellen, zuerst als Einzel, dann 2er-Projekt
- Bestehende Projekte bearbeiten, div. Konstellationen von Prio 1 & 2 Typen & Teamgrössen
