### ISSUE TITLE
Instituts-Externe (nicht i4Ds oder IMVS) Personen zulassen

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#44]
z.B. sollten Dieter Holz oder Christoph Denzler auch Zugriff haben. Die OU bei den beiden ist nicht i4Ds oder IMVS, da Sie im Studiengang Informatik angestellt sind. D.h. Sie haben FHNW Accounts. Es wäre ok, wenn solche User einem spezifischen Institut zugeordnet werden könnten.

Als Workaround wäre auch denkbar, den "Studiengang Informatik" als eigenes Institut zu erfassen.

**Comment by dgruntz** [comment]
Ich könnte mir vostellen dass man die Personen normla über das AD authentifiziert und, falls sie der Gruppe IMVS oder I4DS angehören, dann die entsprechende Gruppe setzen, und ansonsten die Zuordnung aus einem File übernimmt (also für Personen die keiner der beiden Gruppen angehören, aber trotzdem unter dem einen oder anderen Institut Projekte publizieren wollen). Ich denke das ist einfacher als generell eine weitere Organisationseinheit dem IMVS und/oder dem I4DS zuzuschlagen.

**Comment by StephenRUK** [comment]
Benutzer in der AD OU des Studiengangs Informatik sind bereits berechtigt. Diese werden nun standardmässig dem IMVS zugewiesen.

**Comment by StephenRUK** [comment]
Bemerkungen zur Authentisierung:

- Möglichkeit 1: Benutzer ist in i4Ds oderr IMVS OU
- Möglichkeit 2: Falls 1 nicht eintrift, wird überprüft ob ein Eintrag in der Tabelle "UserDepartmentMap" existiert mit E-Mail des Benutzers & einer Department ID.
