### ISSUE TITLE
Export aller Projekte pro Semester: Bereits fest vergebene Projekte sollten am Ende (en Block) aufgelistet werden

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#45]
Die Studierenden sind i.A. nicht an den fix zugeteilten Projekten interessiert. Diese sollten daher alle am Ende der Projektliste aufgeführt werden.

**Comment by dgruntz** [comment]
Ob ein Projekt fix zugeteilt ist erkennt man daran, ob in den Feldern "Reserviert für (optional)" ein Name erfasst ist.
