### ISSUE TITLE
Inkonsistenter Zeilenabstand im PDF

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#47]
Bei der Generierung des PDFs wird bei der Section "Problemstellung" ein etwas kleinerer Zeilenabstand verwendet wie bei den anderen beiden Sections ("Ausgangslage" und "Zielsetzung"). Ich fände es schöner wenn der Zeilenabstand bei "Problemstellung" gleich ist wie jener bei den anderen Abschnitten.

**Comment by deiruch** [comment]
Absätze mit Links weisen immer noch inkonsistente Zeilenabstände auf, z.B. bei "i4Ds18: Mit Machine Learning Immobilienpreise schätzen"

**Comment by dgruntz** [comment]
Anbei ein Beispile wleches dieses Problem zeigt:

![image](https://cloud.githubusercontent.com/assets/1516800/21080479/83e4c934-bfb0-11e6-934c-8f46125f71e5.png)

Interessant ist, dass hier der Zeilenabstand zwischen 1/2. und zwischen 2./3. Zeile grösser als der Normalabstand ist.

Frage: Kann hier nicht ein fixer Zeilenabstrand verwendet werden?

**Comment by flavio99** [comment]
Ich habe es vorläuftig so gemacht, das der Link in einer kleineren Schrift dargestellt wird und so die Zeilenabstände wieder einigermassen konsistent sind.
