### ISSUE TITLE
Projekttypen

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#48]
Für das IMVS sollen zwei neue Projekttypen erfasst werden:
- Sys/Sec	(ITSM, Networks, Security, ...)
- SE	(Software Engineering, Testing, Tooling, Architectures, ...)

Die Datei AddNewProject.aspx habe ich im Commit 6bf3bce18ba3012089a8458dd4b7e18778764385 bereits vorbereitet (Zeile 163-166), aber was noch fehlt sind die 4 Bilder und die beiden Methoden SysSec_Click und SE_Click und die Erweiterung des Arrays private bool[] projectType = new bool[6]; auf Länge 8.

Ob sonst noch Anpassungen nötig sind kann ich gerade nicht beurteilen.

**Comment by deiruch** [comment]
Die beiden Themen sollten nur für's IMVS-User sichtbar sein.

**Comment by dgruntz** [comment]
Willst Du das wirklich für das i4DS einschränken? Ich hätte das für alle offen gelassen, auch umgekehrt dass alle Kategorien bei den IMVS Mitarbeitern sichtbar sind (auch wenn gewisse voraussichtlich nie gewählt werden).

**Comment by StephenRUK** [comment]
Falls in Zukunft weitere Typen dazukommen - Notizen zu den Bildern:

- Bildgrösse: 640x400
- Schriftart: Arial 130px, schwarz, mittig

- "Checked" Hintergrundfarbe: Beliebig
- "Unchecked" Hintergrundfarbe: RGB 230,230,230
- "Unchecked" Layer mit dem Grauwert, Modus "Lighten", 80% Opacity (oder Schriftfarbe direkt setzen ;-) )

**Comment by deiruch** [comment]
@dgruntz: Ja, besser nur für IMVS.
