### ISSUE TITLE
Keine Icons auf den Buttons (Internet Explorer)

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#51]
Unter dem Internet-Explorer werden die Bilder der Buttons nicht richtig dargestellt. Bei den Buttons für "Projekt bearbeiten" und "Projekt löschen" wird gar nichts dargestellt. Scheint dass die Skalierung der Icons auf diesen Buttons nicht richtig ist. 

![image](https://cloud.githubusercontent.com/assets/1516800/15319299/77921bca-1c2a-11e6-80ac-af73aa068bcb.png)

**Comment by deiruch** [comment]
Mit IE version 11 läuft die Webseite bei mir. Mit welcher Version hast Du getestet?

**Comment by dgruntz** [comment]
Ich habe es mit dem IE getestet, welcher auf dem Citrix-Server installiert ist. Es handelt sich um IE Version 11 (11.0.9600.18231) und in dieser Version werden die Icons nicht richtig dargestellt. Dann habe ich es noch im Chrome mit dem IE-Tab probiert, und dort wird es auch nicht richtig dargestellt (ich weiss nicht welche Version da verwendet/emuliert wird).

**Comment by deiruch** [comment]
Dieser Bug und #52 können gefixt werden, mit diesem zustätzlichen Meta-Tag:

`<meta http-equiv="x-ua-compatible" content="IE=edge">`

Die FHNW-Group Policy zwingt IE anscheinend den IE7-kompatibilitäts-Modus per Default auf. Mit diesem Meta-Tag sollte das übersteuert werden können.
