### ISSUE TITLE
Layout (Internet Explorer)

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#52]
Unter dem Internet-Explorer ist es schwierig, die Labels den Feldern zuzuordnen. Es scheint, dass im Table-Layout etwas durcheinandergekommen ist. Betrifft z.B. das Feld unterhalb von "Kunde", aber auch die Felder in denen der/die Betreuer erfasst werden sollen erscheinen als ziemlich willkürlich plaziert zu sein.

![image](https://cloud.githubusercontent.com/assets/1516800/15319472/5094b77a-1c2b-11e6-97bc-fdac9f6f63a9.png)

**Comment by deiruch** [comment]
Mit IE version 11 läuft die Webseite bei mir. Mit welcher Version hast Du getestet?

**Comment by dgruntz** [comment]
Ich habe es mit dem IE getestet, welcher auf dem Citrix-Server installiert ist. Es handelt sich um IE Version 11 (11.0.9600.18231) und in dieser Version werden die Icons nicht richtig dargestellt. Dann habe ich es noch im Chrome mit dem IE-Tab probiert, und dort wird es auch nicht richtig dargestellt (ich weiss nicht welche Version da verwendet/emuliert wird).
