### ISSUE TITLE
Beim Einreichen Hinweise mit schicken können

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#57]
Ergänzend zu #55 wäre es praktisch, wenn Einreicher/-innen eine kurze Mitteilung (bei Bedarf) mitschicken könnten, und wenn diese Mitteilung ebenfalls in einem Chat-Ähnlichen-Verlauf neben/unten/oberhalb eines Projekts sichtbar wäre.

Vielfach weise ich ein Projekt zurück, weil etwas unklar ist. Dann wäre es manchmal gut, der Einreicher könnte beim 2. Versuch noch erklärenden Text dazuschreiben. Vorallem bei Personen, die selten im Büro sind.

**Comment by Beckicious** [comment]
fixed with b6a256c14b12d944d492e1fcaec75032087e0cf7
