### ISSUE TITLE
Schlechte Fehlermeldung

### ISSUE THREAD

**Issue by flavio99** [i4Ds/ProStudCreator#58]
Wenn ich mich beim Prostudcreator einloggen will, kommt eine schlechte Fehlermeldung. Die Fehlermeldung sollte genau beschreiben was man tun soll.

![schlechter_fehler](https://cloud.githubusercontent.com/assets/17273963/15673128/dcbdca20-2734-11e6-9d53-98988898f481.JPG)

**Comment by StephenRUK** [comment]
Um eine eigene "Zugriff verweigert" Seite anzuzeigen habe ich "custom errors" aktiviert. Dies führt dazu dass die interne Fehlermeldung nicht angezeigt wird.

Für den Moment kannst du diese bei dir deaktivieren, siehe dir dazu web.config an (customErrors off setzen :-) )

**Comment by deiruch** [comment]
Allerdings sieht niemand die "Zugriff verweigert" Seite, alle sehen nur diese gelbe Seite. Wolfgang Weck und Norbert Seyff wurden von dieser Seite begrüsst...

**Comment by StephenRUK** [comment]
Auch seit dem Fix in #54 ?
Die Fehlerseite erscheint wenn ich mich mit meinem Studentenkonto einlogge. Allerdings fällt mir jetzt ein, dass dort die Berechtigungsabfrage gar nicht gemacht wird, da "isStaff" bereits false ergibt (2. Bedingung wäre dann ob die Abteilung ok ist)

**Comment by StephenRUK** [comment]
Eureka -> Habe einen Fehler gemacht mit dem Nullcheck, hab den Elvis-Operator falsch eingesetzt und das führte dann auf der Fehlerseite selber zu einem Fehler *facepalm* :-)
