### ISSUE TITLE
Eigene Projekte gesondert auflisten (auch veröffentlichte)

### ISSUE THREAD

**Issue by StephenRUK** [i4Ds/ProStudCreator#59]
Momentan werden eigene (= man ist Ersteller/Betreuer/Kunde) Projekte wie folgt aufgelistet:
- Unter "Eigene, nicht eingereicht" während der Bearbeitung oder falls eingereicht & abgelehnt
- Unter "Eigene, eingereicht" wenn eingereicht
- Eigene, veröffentlichte Projekte sind in der Liste der Projekte des nächsten Semesters

Es könnte nützlich/sinnvoll sein, die eigenen Projekte auch im letzten Fall gesondert anzuzeigen.
Allenfalls könnten eigene Projekte zusammen aufgelistet werden mit einer Farbcodierung für den Status und evtl. Ausblenden der "Bearbeiten" und "Löschen" Buttons.

**Comment by deiruch** [comment]
Martin Kropp wünscht sich das Feature auch.
