### ISSUE TITLE
Neue Felder in Datenbank

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#61]
Für spätere Erweiterungen sollten diese Daten in der Datenbank gepseichert werden können:
- Wurde gewählt/nicht gewählt
- Welche Studis haben das Projekt übernommen
- Ist es ein IP5/IP6
- Wird das Projekt Vollzeit, Teilzeit, 6a oder 6b durchgeführt?
- Ist das Projekt verrechenbar? (Einer von 6 möglichen Gründen)

Dazu bitte neue Felder in DB einführen (nullable).

**Comment by deiruch** [comment]
Ablehnungsgründe:
- Ausbildungsstätte
- bb-Arbeitgeber
- KTI
- IP5 wird zu IP6
- ohne Verrechnung vereinbart
- OpenSource Projekt
- ungenügend für Rechnung
- abgebrochen

**Comment by StephenRUK** [comment]
Habe Änderungen an der DB lokal vorgenommen und getestet - keine Fehler entdeckt. Änderungen wurden soweit auf der Test DB und Webseite übernommen.

**Comment by StephenRUK** [comment]
Felder sind nun auch auf der produktiven DB & Webseite vorhanden. Done.

**Comment by StephenRUK** [comment]
`CREATE TABLE [dbo].[Experts](
	[id] [int] NOT NULL IDENTITY (1,1) PRIMARY KEY,
	[Name] [nvarchar](100) NOT NULL,
	[Mail] [nvarchar](100) NOT NULL)


CREATE TABLE [dbo].[BillingStatus](
	[id] [int] NOT NULL IDENTITY (1,1) PRIMARY KEY,
	[DisplayName] [nvarchar](50) NOT NULL)

INSERT INTO BillingStatus (DisplayName) VALUES
	('Ausbildungsstätte'),
	('bb-Arbeitgeber'),
	('KTI'),
	('IP wird zu IP6'),
	('ohne Verrechnung vereinbart'),
	('OpenSource Projekt'),
	('ungenügend für Rechnung'),
	('abgebrochen')


ALTER TABLE Projects ADD
	PreviousProjectID int NULL,
	ClientAddressStreet nvarchar(100) NULL,
	ClientAddressPostcode nvarchar(10) NULL,
	ClientAddressCity nvarchar(100) NULL,
	BillingStatusID int NULL,
	LogProjectTypeID int NULL,
	LogProjectDuration tinyint NULL,
	LogStudent1Name nvarchar(100) NULL,
	LogStudent1Mail nvarchar(100) NULL,
	LogStudent2Name nvarchar(100) NULL,
	LogStudent2Mail nvarchar(100) NULL,
	LogExpertID int NULL,
	LogExpertPaid bit NULL,
	LogDefenceDate datetime NULL,
	LogDefenceRoom nchar(10) NULL

ALTER TABLE Projects ADD
	CONSTRAINT FK_PreviousProject FOREIGN KEY (PreviousProjectID)
		REFERENCES Projects (Id),
	CONSTRAINT FK_Expert FOREIGN KEY (LogExpertID)
		REFERENCES Experts (Id),
	CONSTRAINT FK_BillingStatus FOREIGN KEY (BillingStatusID)
		REFERENCES BillingStatus (Id)
`
