### ISSUE TITLE
Einreichen

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#64]
Christoph Stamm hat versucht, ein Projekt einzureichen, und dann kommt die Fehlermeldung

![image](https://cloud.githubusercontent.com/assets/1516800/15800142/16b99232-2a72-11e6-88a0-e40ed02fa02c.png)

Bei den anderen Projekten war es möglich ein Bild ohne Beschriftung einzufügen.

Es handelt sich um das Projekt https://www.cs.technik.fhnw.ch/prostud/AddNewProject?id=180.

**Comment by deiruch** [comment]
Sollte jetzt funktionieren. Ich habe das Projekt gleich eingereicht.
