### ISSUE TITLE
Sortierung PDF AllProjects

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#66]
Aktuell werden die Projekte im generierten PDF File nach Instituten gemischt dargestellt. Ich fände es schöner, wenn die Projekte nach Nummern (und damit aich nach Instituten sortiert) aufgelistet werden, 

Dass die vergebenen Projekte am Schluss sind, das finde ich weiterhin gut!

Ich denke, man müsste einfach die Sortierbedingung anpassen.

**Comment by deiruch** [comment]
Obwohl dann alle IMVS-Projekte erst in der zweiten Hälfte zu sehen wären?

Evtl. würde eine thematische sortierung mehr Sinn machen?

**Comment by dgruntz** [comment]
Dass dann die IMVS Projekte später kommen ist egal. Man könnte (wenn nötig) dann auch einfach zwei Dateien daraus machen -- kann man jetzt zwar auch, aber es ist einfacher wenn die Titel gemäss Institut sortiert sind.

Eine Thematische Sortierung (oder bereits eine Sortierung nach Betreuer, denn das impliziert häufig auch eine thematische Sortierung) ist wohl etwas das wir in einer späteren Version anschauen müssen.

**Comment by deiruch** [comment]
Fixed.
