### ISSUE TITLE
Feldbegrenzung

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#69]
Das Abschneiden der Eingabe in den Feldern Ausgangslage/Ziel/Problemstellung etc. ist gefährlich falls ein Nutzer den Text per copy/paste aus einer Vorlage kopiert. Ein Beispiel ist das Projekt i4Ds11 (HS16), dort ist jetzt der Text in der Ausgangslage einfach abgeschnitten.

Variante wäre, dass alle Zeichen dargestellt werden, dass aber beim Speichern eine Fehlermeldung kommt dass der entsprechende Text zu lang ist. Variante ist die Längenbegränzung vollständig rauszunehmen und nur zu prüfen, ob alles auf einer A4-Seite platz hat.

**Comment by deiruch** [comment]
Bin für Variante B: Längenbegrenzung rausnehmen und nur beim EINREICHEN prüfen. (Nicht beim Speichern).

**Comment by dgruntz** [comment]
Finde ich gut. Habe ich so gemeint (aber nciht so geschrieben).
Ich weiss nicht wie die Felder in der DB abgelegt sind, aber ein VARCHAR(1000) ist dann natürlich nciht mehr möglich.
