### ISSUE TITLE
"Projektliste in Excel" liefert nur die Projekte des nächsten Semesters

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#72]
Auf jeder Seite (d.h. bei jedem Tab "vergangenes Semester", "laufendes Semester" etc) sind unten folgende Buttons eingefügt.
![image](https://cloud.githubusercontent.com/assets/1516800/17810114/5791100c-661b-11e6-96e2-3752862bc9ed.png)

Der Button "Projekte als PDF" bezieht sich dabei auf die aktuelle Semesterwahl ("laufende Semester", "nächstes Semester", etc.)
Der Button "Projektliste in Excel" liefert jedoch (offenbar) immer das Excel der Projekte aus "nächstes Semester" (aktuell also gerade eine leere Liste).

Ich denke, diese Buttons sollten sich konsistent verhalten umd am besten die Liste der aktuellen Einstellung liefern.

**Comment by deiruch** [comment]
Fixed.
