### ISSUE TITLE
PDF Export der Projekte

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#73]
Ich könnte aus ProReg, also der Applikation in welcher die Studierenden die Projekte wählen auch direkt auf die PDFs der einzelnen Projekte verweisen. Dazu bräuchte ich allerdings einen Link auf einzelne PDFs. Ich denke es ist nicht sinnvoll, dazu direkt auf ProStud zu verweisen (da diese PDFs bei jedem Zugriff generiert werden), aber ich könnte die PDFs lokal auf dem WebServer abspeichern. Dazu bräuchte ich jedoch die Funktion welche diese PDFs generiert und einzlen (z.B. in einem zip-File) zusammenstellt. Als Name / URL dieser Files könnte man entweder "Kürzel.pdf" nehmen, oder man könnte auch das Feld "Display-Name" umfunktionieren.

**Comment by deiruch** [comment]
Über https://www.cs.technik.fhnw.ch/prostud/PDF?dl=false&id=29 kann man nun direkt PDFs anzeigen lassen. Mit `dl=true` wird ein Download des PDFs mit korrektem Dateinamen forciert. Benutzer müssen sich beim Ersten PDF evtl. authentifizieren und es können von Studis nur veröffentlichte Projekte betrachtet werden (aus allen Semestern).

Im Excel-Export (der neu die aktuell angezeigte Liste exportiert) wird neu u.A. auch die ID mit rausgeschrieben (Spalte 15).

Ich hoffe, das taugt so?
