### ISSUE TITLE
Suche nach Studierenden

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#76]
Christoph Denzler möchte schnell nach Studis suchen können und deren Projekte aufgelistet bekommen.

**Comment by deiruch** [comment]
Die aktuelle Implementation ist noch nicht wirklich nützlich, da man die Namen der Studierenden gar nicht sieht...

Zudem ist die Interaktion mit den Filter-Kriterien intransparent. Es ist z.B. nicht klar, ob der Filter für die Suche gilt, oder nicht. Wenn man den Filter wechselt, sieht man wieder alle Projekte, aber im Suchfeld steht weiterhin der Suchbegriff.

Und vielleicht sollte man die Suche sowieso verallgemeinern, so dass auch nach Titeln, Betreuern, etc. gesucht werden kann?

**Comment by deiruch** [comment]
Beispiel: Suche nach "Grubenmann" in "Alle Semester"/"Veröffentlichte Projekte" ergibt keine Resultate, obwohl Id=120 gefunden werden müsste.

**Comment by JonasDev99** [comment]
Nein, das Projekt enthält keine Reservation für einen Studenten...

**Comment by deiruch** [comment]
Wurde aber diesen Studis zugeteilt (LogStudent1Name bzw. LogStudent2Name bzw. -Mail)

**Comment by JonasDev99** [comment]
Ok, die aktuelle Suche durchsucht nur die Reservationen, muss ich wohl noch anpassen.
