### ISSUE TITLE
Silbentrennung bei URLs

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#8]
Die Silbentrennung versagt aktuell bei URLs. Lange URLs sollten aus Layout-Gründen aber umgebrochen werden können, der Link aber weiterhin anklickbar (und lesbar) sein.

**Comment by StephenRUK** [comment]
Siehe Extensions.cs:410 ToLinkedParagraph(). Potenziell Zeilen 450-470
