### ISSUE TITLE
DB: Merge IsContinuation & PreviousProject

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#82]
In der Datenbank existiert aktuell sowohl das Flag "IsContinuation", und die Referenz "PreviousProject". Wenn ein Projekt eine Fortsetzung eines früheren Projekts ist, dann sollte sowohl das Flag, wie auch die ID des Vorgängerprojekts gesetzt sein. --> Redundanz

Vorschlag: "IsContinuation"-Flag entfernen.

**Comment by flavio99** [comment]
In der DB haben im Moment 11 Projekte das IsContinuation-Flag. Von diesen 11 Projekt hat jedoch nur ein Projekt ein PreviousProject eingetragen. 
Gibt es einen sicheren Weg um das Vorgängerprojekt fehlerfrei zu bestimmen?

**Comment by dgruntz** [comment]
"IsContinuation"-Flag wird nicht verwendet und könnte entfernt werden, das ist richtig so.
