### ISSUE TITLE
Projekterfassung "PreviousProject"

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#83]
Man sollte auswählen können, dass ein Projekt eine Fortsetzung eines früheren Projekts ist. Dann sollten automatisch dieselben Studierenden eingetragen werden, die das Vorprojekt durchgeführt haben.

Zur Auswahl sollten nur IP5 stehen, die tatsächlich durchgeführt wurden.

**Comment by flavio99** [comment]
Man kann noch keine VorgängerProjekte auswählen!
