### ISSUE TITLE
NullReferenceException beim Generieren der Projektliste in Excel

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#87]
Ich habe (zugegeben: aus Versehen) bei meinen eigenen Projekten auf den Knopf "Projektliste in Excel" geklickt und dann den untenstehenden Fehler erhalten (NullReferenceException). Eigentlich bin ich ja froh über diese Exception, sonst hätte ich vielleicht noch die falsche Datei an die Studierenden publiziert. Trotzdem: Dem Informatikerherz in mir will das nicht so recht gefallen. Für mich ist es ein Feature, aber eigentlich ist es ein Bug :-)

![image](https://cloud.githubusercontent.com/assets/1516800/21257960/0b71698e-c37b-11e6-8651-749f5650f280.png)

    [NullReferenceException: Object reference not set to an instance of an object.]
       ProStudCreator.ExcelCreator.projectToExcelRow(Project p, IRow row) +46
       ProStudCreator.ExcelCreator.GenerateProjectList(Stream outStream, IEnumerable`1 _projects) +343
       ProStudCreator.Projectlist.AllProjectsAsExcel_Click(Object sender, EventArgs e) +615
       System.Web.UI.WebControls.Button.OnClick(EventArgs e) +11761916
       System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +149
       System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +6015

**Comment by dgruntz** [comment]
Ich vermute dass dies mit 0423e53 korrigiert worden ist.

**Comment by flavio99** [comment]
Ja habe aus Versehen die falsche Issue Nummer in die Commit Nachricht geschrieben.
