### ISSUE TITLE
Verständlichere Fehlermeldung für nicht i4Ds-/IMVS-Mitarbeiter

### ISSUE THREAD

**Issue by deiruch** [i4Ds/ProStudCreator#9]
Nicht i4Ds-/IMVS-Mitarbeiter kriegen momentan eine sehr kurze & technische Fehlermeldung, wenn sie versuchen sich einzuloggen. Eine freundlichere, hilfreichere und schönere Fehlerseite wäre gut.

Zu Debugging-Zwecken wäre auch nützlich, wenn die Abteilung eines betroffenen MAs auf der Fehlerseite aufgeführt würde.

**Comment by StephenRUK** [comment]
Es wird nun eine "freundliche" Fehlerseite angezeigt wenn der Benutzer nicht berechtigt ist. Login und Abteilung werden ausgegeben.

![prostud_custom_403](https://cloud.githubusercontent.com/assets/9080475/14671512/6c0e5edc-06f2-11e6-8803-bc833d7f9b7e.PNG)
