### ISSUE TITLE
Semester Tabelle sollte Verteidigungsdaten für IP6 Variante 2 Semster haben.

### ISSUE THREAD

**Issue by flavio99** [i4Ds/ProStudCreator#92]

**Comment by deiruch** [comment]
Die Termine sollten auch auf der Projekt-Infoseite verwendet werden (für IP6, Variante B/2 Semester).

**Comment by deiruch** [comment]
Dominik Gruntz:

> Martin hat mich noch darauf aufmerksam gemacht, dass auf der Terminliste die Termine für die Verteidigungen IP6-Variante 2 fehlen. Diese findet statt in KW 02/03, also 08.01.18-20.01.2018.
> Im  Sommer finden die Verteidigungen für Variante B im selben Zeitfenster wie die Verteidigungen der normalen Bachelor-Projekte statt.
> 
> Für die Tabelle wird das jetzt eine Herausforderung….
> 
> Vielleicht hilft es, die Zeile Verteidigung IP6 vor die Zeile Abgabe IP6 (Variante 2Sem) aufzuführen und dann unter Abgabe IP6 (Variante 2 Sem) noch eine Zeile mit der Verteidigung IP6 (Variante 2 Sem) einzuführen. Das macht bei allen Kolonnen Sinn, bei den Projekten die im HS starten ist dann die Verteidigung einfach gleich wie die Daten in der Kolonne rechts daneben (bei IP6 (normal)).
> 
> Auch bei der Ausstellung Bachelor-Arbeiten fehlt in der Tabelle eine Zeile bei IP6 (Variante 2Sem)
> 
> Vielleicht wäre es dann nützlich, die Zeilen chronologisch zu sortieren. Was man auch noch aufführen könnte ist das Startdatum (ist gleich wie der Start des jeweiligen Semesters). 
> [Termine_IP56.xlsx](https://github.com/i4Ds/ProStudCreator/files/957769/Termine_IP56.xlsx)
