### ISSUE TITLE
Termine Tabelle ist nicht übersichtlich

### ISSUE THREAD

**Issue by flavio99** [i4Ds/ProStudCreator#93]
Sollte irgendwie aufgeteilt werden können, damit sie nicht so gross/unübersichtlich wird.

**Comment by deiruch** [comment]
Evtl. genügt einfärben?

**Comment by flavio99** [comment]
Evtl. Es kommen aber noch 2 Weitere Spalten hinzu die bereits in der DB sind.

**Comment by deiruch** [comment]
Vorschlag von Dominik Gruntz:

> Vielleicht wäre es dann nützlich, die Zeilen chronologisch zu sortieren.

**Comment by flavio99** [comment]
Idee von Markus Oehninger:
1. Chronologsch (wie oben erwähnt)
2. Alle Abgaben-Termine (auch TiteländerungsTermine) in einer "aufklappbaren" Zeile zusammenfassen. (Für IP5 und IP6 jeweils 4 Termine).
Bsp.
![grafik](https://cloud.githubusercontent.com/assets/17273963/25625142/066cf15e-2f5c-11e7-822b-912a36dac559.png)

**Comment by flavio99** [comment]
Man könnte die Tabelle so färben dass schon vergangene Termine eine Farbe haben und Termine die in nächster Zeit passieren eine andere Farbe.
