### ISSUE TITLE
Trimming of email addresses

### ISSUE THREAD

**Issue by dgruntz** [i4Ds/ProStudCreator#99]
Ich habe auf ProStud unter Admin alle Projekte mit Start 17FS runtergeladen (siehe beiliegendes File). Dabei ist mir aufgefallen, dass in Zelle H45 eine Email-Adresse seht (martin.kimmig@students.fhnw.ch) die jedoch noch zwe CR enthält, d.h. der Inhalt dieser Zelle sieht wie folgt aus:

"martin.kimmig@students.fhnw.ch

"

Ich weiss nicht wie das passiert ist, aber EMail-Adressen sollten beim erfassen mit trim gekürzt werden (d.h. alle leading/trailing blanks/CR/TABs sollten abgeschnitten werden).

Beilage:
[17FS_IP56_Informatikprojekte.xlsx](https://github.com/i4Ds/ProStudCreator/files/944022/17FS_IP56_Informatikprojekte.xlsx)

**Comment by deiruch** [comment]
Ist in der DB gefixt. Aktuell gibt es kein UI für diese Einträge, daher ist der Fehler beim manuellen Import in die DB passiert. Ich schliesse das Ticket daher bis auf weiteres.

**Comment by dgruntz** [comment]
Kann es sein, dass in der Import-Datei (mit der die Studierenden erfasst werden) so eine Unregelmässigkeit drin war, d.h. müsste man allenfalls beim import ein trim() machen?

**Comment by deiruch** [comment]
Der Import passiert von Hand. Das heisst man muss manuell ein trim() machen :)

Die Daten stammen ja aus unterschiedlichen Quellen (Excel-Sheets von Markus, Nachzügler, Updates via E-Mail, ...), daher lässt sich das Problem für den moment noch nicht lösen. Mit einem UI wird das Problem nicht mehr auftreten, da wir hoffentlich keine Multiline-Textareas für einzelne Mail-Adressen in das UI einbauen werden :)

**Comment by deiruch** [comment]
Ich habe mit SQL Check Constraints sichergestellt, dass die Email-Adressen korrekt sind (ohne Newlines, mit @students.fhnw.ch Suffix, etc..). Damit habe ich noch 6 weitere Problematische fälle entdeckt, und gefixt.

In Zukunft wird die DB die Konsistenz sicherstellen.
